### ISSUE TITLE
class Multiplexer

### ISSUE THREAD

**Issue by zzawadz** [mlr-org/mlr3pipelines#10]
The concept.md file describes a class called `Multiplexer`. I think it might be an interesting thing, so I just wanted to define here some of its use cases. 

Feel free to extend this is. I think it will be much easier to define the `Multiplexer`, when we will see how it can be used.

Case 1:
```
## Select one transformation from a few alternatives
      B1
A --> B2  - -> C --> ... -> result
      B3
```

Case 2:
```
## Select one algorithm from a few alternatives
## C1-C3 - different algorithms
## useful for finding the best type of model
## e.g C1 is glmnet, C2 - random forest, C3 - something else)

             C1
A --> B  --> C2 --> result
             C3 
```

## Possible problems?
- make sure that each alternative returns the same object? (is it a real issue?)
- parameterization (defaults, etc?), important for tuning. 
  - how to parameterize the multiplexer for tuning? Eg. If A1 is selected use tune params `a,b,c`, for A2 `d,f` and so on. Do we need to be able to define sth like this?

**Comment by pfistfl** [comment]
So w.r.t. to your problems. 
> same object

- Case1: We define the output of each operator, so we just have to have a strict specification of possible outputs.
- Case2: Everything returned is a `mlr model` object, thus not important.

> Parameters

The multiplexer already exists in `mlr`, see: 
https://github.com/mlr-org/mlr/blob/master/R/ModelMultiplexer.R and
https://github.com/mlr-org/mlr/blob/master/R/ModelMultiplexerParamSet.R

**Comment by zzawadz** [comment]
I'll take a look on that.

**Comment by pfistfl** [comment]
I am sorry, I think my previous answer was not very intelligent and fully thought out, my appologies.

- Case1: It is very important that we define a strict specification of possible outputs a `pipeOp` can have. 
              Optimally, this is always a `data.table` or a `Task`

- Case2: We actually need to discuss how this should work out, I think this case is only sensible in 
              combination with tuning ? 

We have two options with **parallel** `pipeOps`. 
- Either use a Multiplexer, and select **one** of the options. (This can then be tuned)
- Or evaluate all options and for example **stack** / **ensemble** the results.

**Comment by berndbischl** [comment]
same issue as #84 

unify all relevant comments and descibe the concept first in concept.rmd
