### ISSUE TITLE
should PipeOps really have "id" in constructor?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#111]
maybe we should keep API minimal here. 

there only needs to be a settable AB for "id"?

**Comment by mb706** [comment]
`mlr3` currently takes the `id` as an optional parameter in its Learner constructors, e.g. in [`LearnerClassifRpart`](https://github.com/mlr-org/mlr3/blob/master/R/mlr_learners_classif_rpart.R). However, there is also the `mlr_learners$get()` method which constructs with the default `id`. The latter would also work for most PipeOps that don't need specific initialization parameters (E.g. `PipeOpCopy`, `PipeOpLearner`). To what degree should we emulate `mlr3`'s behaviour?

**Comment by berndbischl** [comment]
i agree we should be consistent.
@mllg shall we remove the id in the learner constructor in mlr3? AB is enough?

**Comment by mllg** [comment]
Is this something we might re-add afer discussing the degree of syntactic sugar we want to support? If yes, I would like to postpone this decision.

**Comment by berndbischl** [comment]
IMHO i think this can be removed forever, just cast your vote. if you want to keep it (in both projects) i would close here, but i dont really see the need for it and we become slimmer by removing

**Comment by mb706** [comment]
I think it is need to set things that are not param_vals in the constructor, then one can directly add PipeOps to a graph without having to worry about ID clashes.
```r
Graph$new()$
  add_pipeop(PipeOpScale$new("one"))$
  add_pipeop(PipeOpScale$new("two"))$
  add_edge("one", "two")$
  train(unscaled)[[1]] -> doublescaled
```

**Comment by mb706** [comment]
```r
scale_one = PipeOpScale$new()
scale_one$id = "one"
scale_two = PipeOpScale$new()
scale_two$id = "two"
g = Graph$new()$
  add_pipeop(scale_one)$
  add_pipeop(scale_two)$
  add_edge("one", "two")
```

```r
g = Graph$new()$
  add_pipeop({p = PipeOpScale$new() ; p$id = "one"; p})$
  add_pipeop({p = PipeOpScale$new() ; p$id = "two"; p})$
  add_edge("one", "two")
```

**Comment by mb706** [comment]
This currently makes use of the wonderful `Dictionary$get(key, ...)` functionality and should not be changed.
