### ISSUE TITLE
PipeOps, channel names

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#113]
PipeOp train and predict should always return a named list of results, named with channel names.
We need this, so in graph_fire we can write the results in the correct order into the edge list.

currently, we DO NOT do this, here, which is a very bad bug:

```
  for (id in ids) {
    op = self$pipeops[[id]]
    input = edges[get("dst_id") == op$id, "result"][[1L]]
    res = if (stage == "train") op$train_internal(input) else op$predict_internal(input)
    op$result = res
    edges[get("src_id") == op$id, "result" := list(res)]
  }
 ```

we should
a) document that a pipeop always returns an unnamed list, excatly in the order as its named datatypes are given

b) in PipeOp$train_internal we assert the correct data types and name the list

c) repair graph_fire, where we reorder the result list / write it in correct order in egde list

d) unit test this (e.g. where a user specifies edges in a weird order, but it still works)

**Comment by mb706** [comment]
going for option (a), still needs doc / test
