### ISSUE TITLE
Plot with virtual "input" node, possibly "output" nodes

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#127]
Because otherwise unused channels (that get input during `$train` and `$predict`) will not be visible in plot.

**Comment by pfistfl** [comment]
I would like it, especially for testing and constructing the pipelines.

If @berndbischl absolutely does not want it, maybe add a flag, that enables this

**Comment by mb706** [comment]
did he say he doesn't like it?
