### ISSUE TITLE
as.data.table.DictionaryPipeOp does not work

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#135]
* The `x$ids()` call should really be `x$keys()` now
* the trick with constructing every member does not work and really should not work, because
  1. some PipeOps can't be constructed without further arguments (I guess we could just `try()` this and ignore errors
  1. maybe libraries should be required upon construction? This would make things a bit useless
    * Maybe it would be better to set `packages = ...` in the class itself and get the info out from the `$public_fields` instead of constructing every member

**Comment by pfistfl** [comment]
id, inputs, outputs
