### ISSUE TITLE
implement `predict.Graph` function

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#153]

**Comment by mb706** [comment]
Should only return a single object instead of a list, and throw an error if the graph does not have a single exit.

**Comment by mb706** [comment]
Needs to be expanded when mlr-org/mlr3/pull/267 is through.

**Comment by berndbischl** [comment]
we should not do this only for graphs 
IF we do this, this needs to be consistently handled across mlr3

**Comment by berndbischl** [comment]
currently the s3 sugar should be removed for 0.1, this can be discussed for a later version

**Comment by mb706** [comment]
Removed in bcf98abd12382230661a68d6feae0510408dc73a
