### ISSUE TITLE
Missing PipeOp: PipeOpDropFeatures

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#157]
Removes features based on ...

* their name (e.g., via "keep" and "remove" as regex)
* their storage type

**Comment by berndbischl** [comment]
i edited the typo

**Comment by mb706** [comment]
The corresponding CPO is `cpoSelect`, which has thousands of options for selecting by type, index, regex, keep/remove, etc. It would probably be better instead to have a pipeop that takes a function or R6 object as an argument, and that argument then decides what to select. We could, for example, provide helper functions

```
# exported by mlr3pipeops
sel_by_regex <- function(regex, invert = FALSE, ...) function(cols) {
  xor(invert, grepl(regex, colnames(cols), ...))
}
sel_by_class <- function(classes, invert = FALSE) function(cols) {
  xor(invert, map_lgl(cols, function(x) any(classes %in% class(x))))
}

```
and the user could use it as follows
```
width_selecting_po <- pipeOpSelect$new(sel_by_regex(".*\\.Width"))
factor_removing_po <- pipeOpSelect$new(sel_by_class("factor", invert = TRUE))

# the user can also make his own selector
very_specific_selecting_po <- pipeOpSelect$new(function(cols) { ..... })
```

In theory we could make the selector-function a hyperparameter; the user could then tune over the selection procedure using the paradox trafo functionality.
