### ISSUE TITLE
Missing PipeOp: PipeOpConvertFeatures

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#158]
* logicals to factor
* logicals to integer
* character to factor
* factor to ordered
* restore factor levels

**Comment by jakob-r** [comment]
* factor to integer?

**Comment by berndbischl** [comment]
> * factor to integer?

not really, note that we also have a (very important) FACTOR ENCODING operator. 
in the docs we need to "interlink" these OPs as they do very realted things

**Comment by mb706** [comment]
How is  0d056dd? Still needs tests / doc though.

**Comment by mllg** [comment]
Temporarily moved to attic.

**Comment by berndbischl** [comment]
i do wnat to mention that we need a solution to the problem during the sprint.
this is an essentail operation.

**Comment by berndbischl** [comment]
please write down / link here how the solution should look ike

**Comment by mb706** [comment]
po apply is now in #205

**Comment by mb706** [comment]
PipeOpApply is back in action. Converting features now works like this:
```r
> task = TaskClassif$new("test",
>   data.frame(x = c(T, T, F, F), y = letters[1:4]), "y")
> task
<TaskClassif:test> (4 x 2)
* Target: y
* Properties: multiclass
Features (1):
* lgl (1): x
> gr = Graph$new()$add_pipeop(po("apply",
>   applicator_vector = as.factor,
>   affect_columns = selector_type("logical")))
> gr$train(task)
$apply.output
<TaskClassif:test> (4 x 2)
* Target: y
* Properties: multiclass
Features (1):
* fct (1): x
```
Should there be some "sugar" for this to construct a converter pipeop more straightforwardly?

**Comment by mb706** [comment]
To do: remove applicator_single, instruct user to use `Vectorize`, rename applicator_vector --> "fun".

**Comment by mb706** [comment]
Maybe rename to _PipeOpColApply_

**Comment by berndbischl** [comment]
maybe  PipeOpColApply is a bit more precise? @mllg

**Comment by mllg** [comment]
:+1: for `ColApply` and for removing the scalar applicator.

**Comment by berndbischl** [comment]
>  for `ColApply` and for removing the scalar applicator.

great, agree
