### ISSUE TITLE
Include something like AffectCols in PipeOpPreproc?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#159]

**Comment by mb706** [comment]
kind of exists already but is a bit dumb right now

**Comment by mb706** [comment]
see the `affect_columns` member of `PipeOpTaskPreproc`. Not to be confused with `affected_cols`, lol

**Comment by mb706** [comment]
Depends on mlr-org/paradox#180

**Comment by mb706** [comment]
Implemented in  1cdfc94, still needs documentation / tests. Documentation should refer to Selector.R and probably have some things in common with PipeOpSelect documentation.

**Comment by mb706** [comment]
Things that are to be done here:
- [ ] some `PipeOp`s may have the `affect_columns` parameter even though it does not fit (as a rule, if rows are added/removed, `affect` should probably not work). Check that these call `super$initialize(... can_subset_cols = FALSE)`.
- [ ] some `PipeOp`s call `invoke()` with the parameter values; this paramset needs to have the correct tags and `get_values()` needs to be used. e.g. `PipeOpPCA`.
- [ ] [`expect_datapreproc_pipeop_class`](https://github.com/mlr-org/mlr3pipelines/blob/02617ce90e6574f10f4df1396c22af36a0467c95/tests/testthat/helper_functions.R#L165) should have some tests where it sets `can_subset_cols` to some selectors and checks that the preprocessing does exactly what it is expected to do.

**Comment by mb706** [comment]
(documentation is issue #242 now)
