### ISSUE TITLE
How should model avg ensemble handle `se` prediction

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#160]
It could just calculate the RMS of the `se`s of the incoming predictions. If there were any information on the correlation of these errors it could do better (e.g. if the inputs are are `N` truly independent predictions the resulting `se` could be multiplied by `1/sqrt(N)`).

**Comment by mb706** [comment]
Should probably also incorporate the (weighted) standard deviation of predictions being aggregated.

**Comment by pfistfl** [comment]
Implemented in #161

**Comment by mb706** [comment]
Is it the right way to do things? What if the prediction errors are correlated?

**Comment by pfistfl** [comment]
I guess this is good enough for now?
I mean we do not intend to  solve the problem fully, but instead provide something reasonable.

**Comment by mllg** [comment]
For now, it would be perfectly reasonable to raise an exception if you encounter `se` during averaging. This might be one of the cases where it is better to have fewer features than to have contentious functionality. Keep in mind that somebody will have to maintain it for the next years. 

@berndbischl Agreed?

**Comment by pfistfl** [comment]
Agreement: 
We do not support this for now, this can be a future extension but prio is low.
Closing for now!

**Comment by berndbischl** [comment]
Agree
