### ISSUE TITLE
Integrate vignettes into mlr3book

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#163]
We are doing this / did this for all other packages already.

Rather than putting new vignettes into the package, start directly with the mlr3book. You can also tag it as experimental or add a "rmd-warning" chunk that this is WIP.

**Comment by mb706** [comment]
I estimate this can start next week

**Comment by pfistfl** [comment]
Done

**Comment by pat-s** [comment]
@pfistfl 	Remove the integrated ones from here?

**Comment by pfistfl** [comment]
Done in #161
