### ISSUE TITLE
FeatureUnion after Subsampling

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#173]
In case we wanted to learn Bagging Weights, we would do something like
```r
subsampled_tree = PipeOpSubsample$new() %>>%
    PipeOpLearnerCV$new(mlr_learners$get("classif.rpart"))
  subsampled_tree$pipeops$subsample$param_set$values$frac = 0.7
  pred_set = greplicate(subsampled_tree, 3L) %>>%
    PipeOpFeatureUnion$new(innum = 3L, "union") %>>%
    PipeOpLearner$new(LearnerClassifWeightedAverage$new())
  pred_set$train(tsk)
```

This currently does not work, as FeatureUnion now has different rows in each of its inputs.

**Comment by mb706** [comment]
We would perform union by row IDs, but that would create NAs that the WeightedAverage Learner would still need to handle

**Comment by pfistfl** [comment]
As discussed, this is most  likely not a valid Pipeline.
Closing this for now
