### ISSUE TITLE
PipeOpSubsample needs default other than 1

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#181]
should be `1-exp(-1)`

**Comment by vpolisky** [comment]
@mb706 You mean this line `ParamDbl$new("frac", default = 1, lower = 0, upper = Inf)`?

**Comment by mb706** [comment]
That is part of it. [Here](https://github.com/mlr-org/mlr3pipelines/blob/085d6f38f3e4f23ffa2afb3dc38a0ac83974b028/R/PipeOpSubsample.R#L25-L30) both the "default = 1" and the `ps$values = list(frac = 1, stratify = FALSE, replace = FALSE)` should be changed; not sure if some other point and if tests need to change.

**Comment by vpolisky** [comment]
I made this change (#209), but I think, there's one more related refactoring which could be done. Here:

```
ps = ParamSet$new(params = list(
        ParamDbl$new("frac", default = 1 - exp(-1), lower = 0, upper = Inf),
        ParamLgl$new("stratify", default = FALSE),
        ParamLgl$new("replace", default = FALSE)
      )) 
ps$values = list(frac = 1 - exp(-1), stratify = FALSE, replace = FALSE)
```

we have duplicated code which can be avoided. From what I saw, it seems, that we only need to specify `ps` and create `ps$values` in the `PipeOp` base class from `ps`. But I'm not 100% sure.

**Comment by mb706** [comment]
We had it like this at some point in the past and after long discussions we went to the current state.  One problem is that there are no two people in our group who agree on what the `default` thing in `ParamSet` is _actually_ supposed to mean. imho it is the `default = 1 - exp(-1)` should go, and the ps$values is alright.

Closing this issue since #209 solved it.

**Comment by berndbischl** [comment]
> One problem is that there are no two people in our group who agree on what the `default` thing in `ParamSet` is _actually_ supposed to mean

huh? then it should be written down?

**Comment by mb706** [comment]
Agree
