### ISSUE TITLE
Rename PipeOpBalanceSample

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#187]
Maybe something like "ClassBalanceSample"

**Comment by berndbischl** [comment]
ClassBalancing is shorter or 
PipeOpBalanceClasses

actually we are not necessarily "balancing" classes, as we might also make the distribution less balanced.

I could live with this inconsistency in the name, but maybe better:
PipeOpResampleClasses? 
PipeOpSampleClasses?

**Comment by mb706** [comment]
Decision: "PipeOpClassBalancing"
