### ISSUE TITLE
PipeOpConvert

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#189]
See [284](https://github.com/mlr-org/mlr3/issues/284)

We might want a PipeOp that converts an incoming task to a different task.type via a converter 
specified in some reflections mechanism

**Comment by mb706** [comment]
This would be easy to do by now, the real trouble is that it would not be useful for GraphLearners because the resulting prediction still needs to get converted back to the original

**Comment by pfistfl** [comment]
See #139, started implementation there.

**Comment by pfistfl** [comment]
I guess this is covered via the target trafos, closing here.
