### ISSUE TITLE
we really have to define how data objects flow through the pipeline.

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#19]
currently i can only see this:
- each PO takes a task, transforms it and returns a task
- we have sublclasses for POs, to make the transformation easier.
-- PipeOpFeatureTransformer: Takes a dt and returns a dt  
   contract is that dt is the feature table, nr of rows or targets are not changed.
-- PipeOpTask: Takes a task, returns a task

**Comment by pfistfl** [comment]
So having the [task] -> [task] convention would allow us to work with different  **dataBackends** more sensibly I guess?

The only big "plus" for having [dt]'s is, that it would enable us to do in-place manipulation, i.e. it would not require copying the *dt*.

**Comment by mllg** [comment]
There are already task operations which allow you to modify the task without copying the data.

Rbind/Cbind:

```r
> task = mlr_tasks$get("iris")
> print(task$backend$primary_key)
[1] "..row_id"
> task$cbind(data.table(..row_id = 1:150, foobar = runif(150)))
> task$rbind(cbind(iris[1:2, ], foobar = 99))
> task$data()
       Species Sepal.Length Sepal.Width Petal.Length Petal.Width      foobar
        <fctr>        <num>       <num>        <num>       <num>       <num>
  1:    setosa          5.1         3.5          1.4         0.2  0.82141590
  2:    setosa          4.9         3.0          1.4         0.2  0.70186406
  3:    setosa          4.7         3.2          1.3         0.2  0.01421675
  4:    setosa          4.6         3.1          1.5         0.2  0.48926113
  5:    setosa          5.0         3.6          1.4         0.2  0.33795694
 ---
148: virginica          6.5         3.0          5.2         2.0  0.55896490
149: virginica          6.2         3.4          5.4         2.3  0.99956458
150: virginica          5.9         3.0          5.1         1.8  0.88838436
151:    setosa          5.1         3.5          1.4         0.2 99.00000000
152:    setosa          4.9         3.0          1.4         0.2 99.00000000
```

**Comment by mllg** [comment]
Additionally, you can "overwrite" (I might have to find a better name for this) values:

```r
task = mlr_tasks$get("iris")
update = data.table(..row_id = 1:3, Sepal.Length = 99)
task$overwrite(update)
task$head(4)
```

**Comment by mllg** [comment]
If you just want to replace the data, you can re-initialize the task like this:

```r
data = task$data()
newdata = pca(data)
task$initialize(task$id, DataBackendDataTable$new(newdata), target = task$target_names)
```

I think we might want our own method for this at some point, because the interface for initialization differs between tasks. `task$replace_backend(data)`?

**Comment by mllg** [comment]
Oh, and you can of course remove specific rows and columns via `task$row_roles` and `task$col_roles`. Let me know what additional setters you need frequently.

**Comment by berndbischl** [comment]
@mllg yes an option for a deep copy is needed, which changes the data

**Comment by berndbischl** [comment]
and for now we should only use that

**Comment by pfistfl** [comment]
This looks like it might be useful here: 
https://cran.r-project.org/web/packages/irlba/index.html
