### ISSUE TITLE
PipeOpProxy

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#192]
We want to write a PipeOp that basically "encapsulates" another PipeOp or another Graph. It has a parameter `content` that can be set to a PipeOp/Graph; then the PipeOp behaves as if it were this PipeOp/Graph. The PipeOpProxy routes its input through the `content` and returns the output. The nice thing is that `$param_set$values$content` is a parameter and can be changed; this is useful as an alternative to branching.

train/predict should look a bit like
```r
train = function(input) {
content = self$param_set$values$content$clone(deep = TRUE)
if (inherits(content, "Graph")) {
output = content$train(unname(input), single_input = FALSE)
} else {
output = content$train(input)
}
self$state = content
output
}
predict = function(input) {
content = self$state
if (inherits(content, "Graph")) {
output = content$predict(unname(input), single_input = FALSE)
} else {
output = content$predict(input)
}
self$state = content
output
}
```

**Comment by mb706** [comment]
let `po` be a `PipeOp` or a `Graph`, then
```r
popro = PipeOpProxy$new(innum = nrow(po$input), outnum = nrow(po$output))
popro$param_set$values$content = po
po$train(x) == popro$train(x)  # note x is a list of length nrow(po$input)
                               # and the result is a list of length nrow(po$output)
po$predict(x) == popro$predict(x)
popro$input$train == popro$input$predict == rep("*", nrow(po$input))
popro$output$train == popro$output$predict == rep("*", nrow(po$output))
```
* constructor args: `innum` defaults to 1, `outnum` defaults to 1
* `innum` may be 0, in that case input$name is `"..."` (one vararg input channel)

**Comment by mb706** [comment]
There should probably be a check in the `content` parameter just like e.g. [PipeOpMutate](https://github.com/mlr-org/mlr3pipelines/blob/master/R/PipeOpMutate.R) checks its argument. `content` should be checked that it is a graph or a pipeop, and that its number of input / output rows fits the `innum` / `outnum` given at construction.

**Comment by vpolisky** [comment]
Should `PipeOpProxy` be accepted as `content` of `PipeOpProxy`? From my view, it's technically possible. But is there a meaningful use case for this? And are there maybe other `PipeOp`s which can't be `content` of `Proxy`?

**Comment by mb706** [comment]
It would be a bad sign if `PipeOpProxy` could not be wrapped by a `PipeOpProxy` (i.e. whatever is keeping this from working could also surprise the user at other places), so I think it makes sense to test this even if it is not useful.

**Comment by vpolisky** [comment]
For me, the point is actually if really all `PipeOp`s are `Proxyable`. Or, from another view, if `PipeOpProxy` `is-a` `PipeOp`. 

Let's say, we allow this. Then it's possible to do this (with `poproxy1`, `poproxy2` being `PipeOpProxy`s):

```
poproxy1$content = poproxy2
poproxy2$content = poproxy1
```

which leads to an infinite cycle when calling `poproxy1$train`or `predict`.

**Comment by vpolisky** [comment]
One more related point. This

```
popro = PipeOpProxy$new(innum = nrow(po$input), outnum = nrow(po$output))
popro$param_set$values$content = po
```

looks dangerous to me. But can this be avoided while keeping the rest of how `PipeOp`s work?

My first idea was to do both steps with an acitve field. But then I realized, that `innum` and `outnum` are needed in the constructor. 

Another idea would be to not let instantiate `PipeOp` directly with the constructor, but only with a factory method. Or to postpone calling `super$initialize` to where `content` is set.

**Comment by mb706** [comment]
I think PipeOpProxy should behave like any other PipeOp and is not a special case.  
> ```
> poproxy1$content = poproxy2
> poproxy2$content = poproxy1
> ```
that is a really cool example, I guess `poproxy1$content =poproxy1` is even shorter (the Quine proxy), but we want to let the user shoot himself in the foot if he chooses to.

**Comment by mb706** [comment]
We can't avoid having to construct `PipeOpProxy` with the correct number of inputs and outputs, because the point of having the proxy is to be able to change the "content" after the Graph was already built. So we have graphs like
```r
graph = PipeOpCopy$new(2) %>>%
  gunion(list(
    PipeOpScale$new(),
    PipeOpPCA$new()
  )) %>>%
  PipeOpProxy$new(innum = 2, outnum = 2) %>>%
  PipeOpFeatureUnion$new(2)
```
for which we now want to change the behaviour of the "proxy" (e.g. when tuning the Graph). However, the proxy is already in the graph, so we can't change the number of inputs or outputs.

**Comment by vpolisky** [comment]
Yes, this is exactly the problem I have: We can set any `PipeOp` for `content`. In particular, one that is already in the graph. And this can change inputs and outputs. So, maybe it then makes sense to only allow unconnected `PipeOp`s as `content`?

**Comment by vpolisky** [comment]
Basically, the inputs and the outputs of the content should be adapted to the ones of the proxy.

**Comment by mb706** [comment]
the PipeOp itself doesn't know that it is connected to anything. Basically
```r
graph = PipeOpScale$new() %>>% PipeOpProxy$new()
graph$pipeops$proxy$param_set$values$content = graph$pipeops$scale
```
would result in a graph that applies the `scale` PipeOp twice.

**Comment by mb706** [comment]
The information about PipeOp connections is saved entirely in the `Graph` (in the `$edges` slot), so taking one `PipeOp` from one `Graph` to another, or inside a `PipeOpProxy`, will not make a difference vs. constructing a new `PipeOp`. (Things may get a bit weird because (1) we are not 100% consistent about cloning yet and (2) cloning in R6 is broken: r-lib/R6#179, but both of these are only relevant once you do weird things that should void your warranty)

**Comment by vpolisky** [comment]
Ok, I see. So, if a `PipeOp` had a reference to `Graph` to which it belongs, it had access also to the edges?

To better explain the issue I had in mind. Let `po1`, `po2` be two `PipeOp`s with incompatible inputs and/or outputs. It's possible in the same `Graph`, isn't it? So, what should be the behavior of a proxy in this case:

```
poproxy$content = po1
poproxy$content = po2
```

The inputs/outputs in the proxy should be updated?

**Comment by mb706** [comment]
Things are much simpler if the PIpeOps don't know what kind of graph they are in and they are constructed with a fixed number of inputs and outputs that don't change through their lifetime. PipeOpProxy takes the number of inputs and outputs it should simulate as a construction argument. If `po1` has the same number of inputs / outputs as `poproxy` then everything is fine, if e.g. `po2` then has a different number of in/outputs an error is thrown. This is basically what happens [here](https://github.com/mlr-org/mlr3pipelines/blob/b2842e822350f70c92bfef5722ecc7a0ffc6365f/R/PipeOpProxy.R#L57-L68) since this function is called by the `custom_check` of the `ParamUty` "content".

**Comment by mb706** [comment]
This is **pretty advanced** but maybe someone familiar with mlr3pipelines can do that? Just go through the comments above, don't bother with the edge cases of self-referencing pipeops and infinite loops for now.
