### ISSUE TITLE
Fix mlr3book section

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#212]
Currently the [following chunks](https://github.com/mlr-org/mlr3book/commit/826e1d516b62aa19bb4d0efca0f9f095715c8e54) are broken after commit 1f8f58dc347e6c4e8e25d947fdb98f2893271efd.
See https://travis-ci.org/mlr-org/mlr3book/builds/567611044.

Please push a PR to the mlr3book :)

**Comment by pfistfl** [comment]
Check if this still holds and submit a PR in the book

**Comment by mb706** [comment]
mlr3book now seems to contain a working pipelines section: https://mlr3book.mlr-org.com/pipelines.html. closing.
