### ISSUE TITLE
Consider putting a list of supported preproc POs into the README

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#214]
Or alternative provide a dominant link to a section in the mlr3book.

People arriving here might look for the "preprocessing" extension of mlr3 and directly finding a list with all supported operations (as POs) might be motivating to continue with mlr3. 

See also https://github.com/mlr-org/mlr3/issues/304#issuecomment-518259176

**Comment by mb706** [comment]
depends on https://github.com/mlr-org/mlr3pipelines/issues/305

**Comment by pfistfl** [comment]
So I included a list of available Pipeops in the `mlr3book`:
https://mlr3book.mlr-org.com/list-pipeops.html

We might want to beautify this once tags are available.

Additionally, I guess we should also have a list of pipeops in the `mlr3pipelines` docs?
Where would that go?
Or is the answer then just 
`r as.data.table(mlr_pipeops)`

**Comment by mb706** [comment]
can the names be turned into links to the documentation?

**Comment by mb706** [comment]
> list of pipeops in the `mlr3pipelines` docs?

Every PipeOp's documentation also links to all other PipeOps in their "see also" section. I don't think we should go beyond that, a table in the vignette (or whatever we have in place of a vignette) is enough imo.

**Comment by mb706** [comment]
This is in the book now.
