### ISSUE TITLE
Missing PipeOp: RemoveConstantFeatures

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#218]
I think be might be able to just use PipeOpFilter for this?

Here is a PR for a matching filter in mlr3filters:
https://github.com/mlr-org/mlr3filters/pull/53

**Comment by mb706** [comment]
Not sure the referenced filter is a good fit for this; I believe the most common use case would be to remove constant non-numeric features, and remove numeric features with a range below a given tolerance, with some choice on how to handle missings [as mlrCPO does it](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_dropConstants.R). I think the filter in the PR would only work for numeric features that are exactly constant (no tolerance) when the "method" is "count", and it would not work for feactors if "method" is "mode".

**Comment by mllg** [comment]
I don't get your point.

* Remove factors with less than N levels: Apply filter on all factor variables (via selector) with method "count", set filter cutoff to N

* Remove integers where > 10% of the observations differ from their mode (like in mlr's removeConstantFeatures): Apply filter on all integer variables (via selector) with method "mode", set filter cutoff to 0.1

You're right that the handling of missing values is still missing, but isn't this just a hyperparameter?

**Comment by mllg** [comment]
We could have a dedicated PipeOp for this, but isn't this conceptually just another feature filter?

**Comment by mb706** [comment]
Maybe the filter would work, but we should think about how we document this, because it is probably a common use case and people might not know that they should solve this with a filter. We could have an entry in `mlr_pipeops` for the PipeOpFilter with FilterDistinctValues set.

**Comment by berndbischl** [comment]
I just looked at the referenced Filter and think this is probably a good and clean idea.
is simply a documentation issue that for people to make them aware of it

**Comment by berndbischl** [comment]
but this will be used in many of our own usecases, so this will be very visible
