### ISSUE TITLE
Naming: PipeOp -> GraphNode -> Graph | Pipeline?

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#22]
Collecting proposals here!

**Comment by pfistfl** [comment]
Basic setup: 
```
  op1 = PipeOpScaler$new()
  
  op2a = PipeOpPCA$new()
  op2b = PipeOpNULL$new()
  
  op3 = PipeOpFeatureUnion$new()
 
  lrn = mlr_learners$get("classif.rpart")
  op4 = PipeOpLearner$new(learner = lrn)
```
### Proposal 1 (From @zzawadz)
```
  root$
    set_next(list(GraphNode$new(op2a), GraphNode$new(op2b)))$
    set_next(GraphNode$new(op3))$
    set_next(GraphNode$new(op4))
```

**Comment by pfistfl** [comment]
The question for Proposals 2-4 would be whether we expect `GraphNode's` or `Pipelines` as inputs.
 
### Proposal 2
I guess this would be the *Keras* way:
```
gg = Graph$new(op1)
gg$add(list(GraphNode$new(op2a), , GraphNode$new(op2b)))
gg$add(GraphNode$new(op3))
gg$add(GraphNode$new(op4))
```
### Proposal 3
Naming it a Pipeline is kind of confusing
```
gg = Pipeline$new(op1, list(op2a, op2b), op3, op4)
```

### Proposal 4
```
gg = op1 %>>% list(op2a, op2b) %>>% op3 %>>% op4
```

**Comment by berndbischl** [comment]
hi it really is hard to respond here, as the issue is not explained?

**Comment by zzawadz** [comment]
To clarify. The `Proposal 1` is based on the current implementation, and I don't know if it's a good solution.

I like the `Proposal 2`, because it's "one step at the time" approach.

The third proposal we might reformulate into an ordinary function `gg = pipeline(op1, list(op2a, op2b), op3, op4)`. I think it would be the most commonly used solution (probably 99% of pipelines will be just simple linear ones).

**Comment by berndbischl** [comment]
is this about the namoing of classes or the api how to construct the graphs or both?

**Comment by pfistfl** [comment]
Both. 

We have to decide whether we 

- Want to have a "Pipeline" Constructor (This could then possibly hide all the Graph/GraphNode stuff from the user. This would be a little inconsistent from a naming perspective.

- We want the Graph constructor API to work with GraphNodes or PipeOp's 

-  How we want the Graph Constructors to look like

One Idea could be to have a Graph Constructor that expects GraphNodes **and** a Pipeline Constructor that expects PipeOp's. The latter could then hide all "Graph-related" stuff from the user.

**Comment by zzawadz** [comment]
> One Idea could be to have a Graph Constructor that expects GraphNodes and a Pipeline Constructor that expects PipeOp's. The latter could then hide all "Graph-related" stuff from the user.

I like this idea. Graph interface for advanced users, and simple pipeline constructor for all others.

In the second case, we can have an ordinary function like `pipeline` which will do the job - `gg = pipeline(op1, list(op2a, op2b), op3, op4)`.

```r
pipeline = function(...) {
  ... # create all nodes etc.
  Graph$new(root)
}
```

**Comment by berndbischl** [comment]
we have reasonable names now
