### ISSUE TITLE
Preproc + ParamSetRanges

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#23]
A current problem in `mlr` that need's to be tackled in `mlr3`:

```
# Ranger + PCA Preprocessing
lrn = makePreprocWrapperCaret("classif.ranger", ppc.pca = TRUE, ppc.thresh = 0.9)
# We set the max  of mtry to "p"
p = getTaskNFeats(some_task)
ps = makeParamSet(
  makeNumericParam("mtry", lower = 0, upper = p),
  makeNumericParam("ppc.thresh", lower = 0.5, upper = 1)
)
lrn = makeTuneWrapper(lrn, ps, ...)
resample(lrn, task)
```

**Current problem:**
After PCA, only `p* << p` features remain. We tune over a largely invalid space.

- @jakob-r Could you quickly explain where exactly earlier problems wrt to symbols in the param set is?
- We should probably be able to design additional parameters that then overwrites/binds to other params during training. 
One example could be:
```
makeNumericParam("mtry.perc", lower = 0.1, upper = 1, overwrites = "mtry", trafo = function(x) x*p))
```

**Comment by jakob-r** [comment]
So basically the old problem: task dependent hyperparams
First: You are aware that we are using paradox and not ParamHelpers in mlr3? Please have a look at it. It can do exactly what you proposed. ([here](https://github.com/mlr-org/paradox#transformations))

Let's look at this this way (hypothetically):
Let's abolish all task dependent params. `mtry`? Our learner won't have this parameter. He will only have `mtry.perc`. What would we have to do? Do some transformations directly before we call the native train function. Technically this would be the easiest solution but is kind of against our rule to just forward the api of the native learner. Unfortunately only just shortly before we train we know the exact size of our datasize.
What we can do instead is to only have the relative (task independent) values in the param set and transform them at the latest possible point given the actual values for `p`, `q` etc. (These stores are saved in the dictionary)
However I am unsure if this generates problems in a nested scenario where `p` changes down the pipeline but is used at different stages.

**Comment by jakob-r** [comment]
Let's discuss everything here:
https://github.com/mlr-org/mlr3pipelines/issues/24

Regarding your question (although I guess you know the answer): You can add any parameter you want and define the trafo so that it generates the params needed by the learner based on your own parameters.
