### ISSUE TITLE
Author List

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#231]
Author names and email addresses.

**Comment by mllg** [comment]
I have updated the author list in b0d915b8c762cf0b2bbd2ff1368fedda0dd12186. @pfistfl, please check your details (and add an orcid if you want). 

NB: I don't care about the order. Reorder as you find appropriate.

**Comment by mllg** [comment]
3390018ea3961ceaa485d369fade005e66403324 with updated author roles.
