### ISSUE TITLE
PipeOp Ideas

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#234]
* [x] [Model Matrix](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_modelMatrix.R) [explanation](https://mlrcpo.mlr-org.com/articles/a_3_all_CPOs.html#cpomodelmatrix)
* [x] [ICA](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_ica.R)
* [x] kernelPCA (kernlab::kpca)
* [x] [ScaleMaxAbs](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_scaleMaxAbs.R)
* [x] [ScaleRange](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_scaleRange.R)
* [x] "smote". [mlr has this](https://github.com/mlr-org/mlr/blob/master/R/smote.R) but we would have to find a package that provides this which is not mlr
* [x] [quantile binning](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_quantileBinNumerics.R)
* [x] histogram binning (bins of equal width instead of equal number of examples)
* [x] box cox transform
* [x] yeo-johnson transform
* [x] [spatial sign](https://github.com/mlr-org/mlrCPO/blob/master/R/CPO_spatialSign.R)
* https://github.com/mlr-org/mlr3pipelines/issues/154 (but this appears to use recipes)

**Comment by pfistfl** [comment]
- [ ] Extract Date Features (c.f. [fast.ai](https://github.com/fastai/fastai/blob/master/fastai/tabular/transform.py)
- [ ] Categorical Variable Encodings

**Comment by mb706** [comment]
are there recommended packages for categorical variable encodings?

**Comment by pfistfl** [comment]
Either use `embed` or use the CPO implementations from the benchmark by Florian Pa.
