### ISSUE TITLE
PipeOp Ideas inspired by "recipes" package

### ISSUE THREAD

**Issue by susanne-207** [mlr-org/mlr3pipelines#254]
* [ ] [Imputation via bagged trees](https://github.com/tidymodels/recipes/blob/master/R/bag_imp.R) 
* [ ] [Isomap Embedding](https://github.com/gdkrmr/dimRed/blob/master/R/isomap.R)
* [ ] [Imputation via kNN](https://github.com/tidymodels/recipes/blob/master/R/knn_imp.R)
* [ ] [Non-negative matrix factorization](https://github.com/renozao/NMF)
* [ ] [Parial least squares dimension reduction](https://github.com/bhmevik/pls) 
* [ ] Remove NA rows

**Comment by pfistfl** [comment]
- [ ] [Feature Crossing](https://tensorflow.rstudio.com/guide/tfdatasets/feature_columns/#crossed-column)

**Comment by sumny** [comment]
I opened separate ones, So I close this issue.
