### ISSUE TITLE
Benchmarking Graph Learners and measuring AUC

### ISSUE THREAD

**Issue by smaakage85** [mlr-org/mlr3pipelines#264]
Thank you so much for your work on 'mlr3' and especially 'mlr3pipelines', it looks like a really promising framework.

I have been working a bit with 'mlr3pipelines' and have a couple of questions for you. Also I have one or two feature requests.

**Feature requests**
- Is it possible to benchmark multiple Graph Learners on the same task? This would be a really useful feature.
- how do you extract data from the original task from a trained 'AutoTuner'. It could be really nice, if one from the AutoTuner could look up for instance the names of the variables in the data set used for training - and their respective roles.

**Bugfix**
- How do you measure ROC AUC for a Graph Learner? I have tried to set up a Graph Learner with a learner with pred_type = "prob", but it fails in training. Is this a known bug? I can make a reproducible example, if there is need for one.

**Comment by berndbischl** [comment]
> * Is it possible to benchmark multiple Graph Learners on the same task? This would be a really useful feature.

of course. the whole idea of the graph learner is that it is an mlr3 Learner. you can benchmark it, tune, and so on. 

> * how do you extract data from the original task from a trained 'AutoTuner'. It could be really nice, if one from the AutoTuner could look up for instance the names of the variables in the data set used for training - and their respective roles.

if this is an Autotuner question probably post it in mlr3tuning. but i am unsure if i get the question. could your example be more specific pls, sorry. or let me try: you have a learner, add an AutoTuner to it. then you train the AutoTuner. Now you want to ask it, what the names of the variables are from the task that you called Autotuner$train on? is that correct?

**Comment by berndbischl** [comment]
> * How do you measure ROC AUC for a Graph Learner? I have tried to set up a Graph Learner with a learner with pred_type = "prob", but it fails in training. Is this a known bug? I can make a reproducible example, if there is need for one.

pls indeed provide the example

**Comment by mb706** [comment]
I think the problem here was https://github.com/mlr-org/mlr3pipelines/issues/306 so closing this issue.
