### ISSUE TITLE
Missing PipeOps

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#265]
- [ ] fix missing factors
- [ ] re-code rare factor levels

**Comment by berndbischl** [comment]
please dont do such "catch all" issue. create a specific issue, in this case about the factor level pipeop, with a good title

**Comment by mb706** [comment]
Its very nice to have this kind of checklist of very closely related issues, because they don't clutter the issue list as badly.

**Comment by berndbischl** [comment]
i still dont want this. you can keep this, but experience tells me that this a bad things. you can use various grouping options instead.
labels, projects, milestones are all there
