### ISSUE TITLE
html plots for linear pipelines are a bit too dense

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#274]
This is a simple linear pipeline, it should probably be vertical going down without overlapping arrows
![htmlplot](https://user-images.githubusercontent.com/15801081/66004339-d6bf2300-e4a8-11e9-8081-c3e730abedc5.png)

**Comment by pfistfl** [comment]
This was due to a bug in `visNetwork`. 
Should be fixed on github / CRAN now. 
(https://github.com/datastorm-open/visNetwork/commit/ecf52d70fc82b92153a641df93c18275e18c6607)
 
I will submit a PR.

**Comment by pfistfl** [comment]
See #279

**Comment by pfistfl** [comment]
Guess we can close here, was merged.
