### ISSUE TITLE
We need to figure out how we handle character features and levels

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#275]
We should probably treat character features as something that may have an unlimited number of levels, leave it out from encoding, fixing factors etc. For factors and ordereds we should trust that `levels(task$data()[[feature]])` is the same as `task$levels()[[feature]]`. In that case we can remove the "levels" argument from the data.table functions of `PipeOpTaskPreproc`.

**Comment by mllg** [comment]
We can do this, if this helps. Currently blocked by `mlr3db`: Many databases do not provide a native type for factors, everything is a character. At least we need an option there to auto-convert character -> factor in the backend.

**Comment by mb706** [comment]
Since https://github.com/mlr-org/mlr3/issues/369 @mllg do you believe this is no longer blocked?

**Comment by mllg** [comment]
I guess.

**Comment by mb706** [comment]
We now consistently handle character features as features without levels.
