### ISSUE TITLE
Dictionary for pipelines

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#277]
There are some usecases that are very common but that require multiple pipeops. E.g. imputation + missing indicator columns require a `copy`, followed by `gunion(list(impute [factors, numerics separately], missingindicators))`, followed by `featureunion`-- which is actually quite advanced for such a simple use case.

It could be useful to have a `mlr_pipelines` or `mlr_graphs` dictionary* that generates (compound) pipelines for these usecases. The entries in that dictionary would have to be functions that get executed when `Dictionary$get()` is executed.

The functions would probably need a few parameters. A common one should be `id`, which gets postfixed (or prefixed?) to pipeop IDs (so `mlr_pipelines$get("impute", id = "abc")` would create things like `copy.abc`, `missind.abc` etc.). The impute case could have parameters `impute_num`, `impute_fact` that take ids (or pipeops?) for the operation of how the specific type should be imputed.

There could be a sugar function, e.g. `pl()`. Hyperparameters could be set through the mlr3misc sugars mechanism which sets the `param_set$values` of the created object (a `Graph` in this case). Therefore it would look like `pl("impute", id = "abc", missind.abc.which = "all")` which sets the `which` parameter of the missing indicators `PipeOp` in the resulting `Graph`.

h/t @Coorsaa for this idea.

*not sure about the name; pipelines would be nice but it is very similar to pipeops, and it is good to avoid very similar names imho

**Comment by pfistfl** [comment]
Second this, we should maybe at at least have a fixup learner pipeline that fixes most common problems:
- imputation (and subsequent unions)
- removing constants
- fixing factor levels
- encoding of categoricals (if required).

Everything with somewhat sensible defaults. I think this would go a long way towards making stuff 
accessible to users.

**Comment by berndbischl** [comment]
i think this is a good idea. we already dicussed maybe having "ready-made pipeline chunks"
- or functions which create these - and this is exactly also what i thought we needed when i watched martins first demos

**Comment by pfistfl** [comment]
I guess this is sovled via #323
