### ISSUE TITLE
Reinstantiating classes

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#28]
So as I understand it, we require to re-instantiate a new task after manipulating the data in the PipeOp's.
I guess it would make sense to have helper functions for this, as in most cases task type and target etc. will stay the same. 

Does anybody see a better alternative?

**Comment by mllg** [comment]
I believe you never need to completely re-instantiate it, as you always keep some parts of the task (either the target or some features). I think you can get pretty far with these operations:

* rbind (add rows)
* cbind (add cols)
* select (subset cols)
* filter (subset rows)
* overwrite (replace values)

These operations are all already available for tasks. Can you think of a situation where you need something else?

**Comment by pfistfl** [comment]
I oversaw that, thanks. I will reopen if this does not suffice

**Comment by pfistfl** [comment]
```
task = mlr_tasks$get("iris")
d = task$data()
task$overwrite(d)
```
