### ISSUE TITLE
Neural Net Builder PipeOps

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#281]
An interesting usecase for PipeOps would be to use them to parameterize deep learning models. E.g.
```r
net_pipe = po("torch.input") %>>%
  po("torch.conv2d", 1, 3, 5) %>>%
  po("torch.relu") %>>%
  po("torch.conv2d", 3, 16, 3) %>>%
  po("torch.relu") %>>%
  po("torch.linear", 16 * 3 * 3, 120) %>>%
  po("torch.relu") %>>%
  po("torch.maxent")
lrn_pipeline = gunion(
  net_pipe,
  po("impute") %>>% po("encode")) %>>%
  po("neural_net_learner")
```

This would look something like
```
 [input] --> [impute] --> [encode] -->  |--------------------|
                                        | neural_net_learner | --> [prediction]
 (conv) -> (relu) -> (conv) -[...] -->  |--------------------|
```
Here the `"torch.*"` PipeOps do not handle any training/prediction data. Instead, during training, they just collect a description of a neural net, which the `"neural_net_learner"` then constructs to a model that is used for training. During prediction, they do not do anything.

This would make it possible to use pipeline searching metalearning techniques to also construct neural network architectures.

We could drive this idea further to also handle nested `PipeOp`s like this. There could be a `PipeOpAutoLearner` that has one input channel for the training / prediction data, and another input channel from where it takes the actual `Learner` / `Graph` that is being tuned. There are some difficulties with this; somehow the autotuner `PipeOp` would have to know about the `Graph` structure, which is unlike the things we have built before, where `PipeOp`s work independently of the `Graph`.

**Comment by pfistfl** [comment]
I feel that if we decide to do this, this should go into a different Package.
Additionally, we would have to think whether `mlr3` / `mlr3pipelines` gives us the flexibility to
work.

**Comment by mb706** [comment]
Exists now as https://github.com/mlr-org/mlr3torch
