### ISSUE TITLE
Most used preprocessing ops according to msft github analysis

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#283]
Sklearn
- StandardScaler
- CountVectorizer
- TfidfTransformer
- PolynomialFeatures
- TfidfVectorizer
- Imputer
- PCA
- RobustScaler
- OneHotEncoder
- SimpleImputer
- MinMaxScaler

ML.NET
- OneHotEncoder
- TfldfTransform
- ImputerTransform
- TokenizerTransform
- CountVectorizer
- HashTransform
- TreeFeatureExtractorTransform
- UDF
- NgramTransform
- CountFeatureSelectionTransform

**Comment by mllg** [comment]
I guess someone needs to make a checklist out of this and create new feature requests for missing pipeops?

**Comment by pfistfl** [comment]
I will just note down what we currently not have here:

`PipeOp's` for  `character (text)` columns:
- [ ] StopWordRemover (sklearn)
- [ ] CountVectorizer (sklearn)
- [ ] TfidfTransformer / TfidfVectorizer (sklearn)
- [ ] NgramTransform (ml.net)

`PipeOp's` for `numeric` columns:
- [ ] RobustScaler (PipeOpScale with `robust` = TRUE?)

Generic `PipeOps`
- [ ] HashTransform (ml.net)
- [ ] TreeFeatureExtractorTransform
- [ ] UDF
- [ ] CountFeatureSelectionTransform

**Comment by pfistfl** [comment]
I guess another point of discussion is: Do `PipeOp's` for text data go in a separate package?

**Comment by mb706** [comment]
I don't think we should start with different mlr3pipelines subpackages yet. Once there are either a lot of them that clearly don't belong here, or maintenance becomes difficult because of too many dependencies we could change that policy but right now I think it would just be unnecessary overhead.

**Comment by mb706** [comment]
Someone please open a separate issue for each of the checkboxes in @pfistfl's message above so we can have separate discussions.

**Comment by sumny** [comment]
I opened separate ones, so I close this issue here.
