### ISSUE TITLE
GraphLearner does not use same response type as PipeOpLearner

### ISSUE THREAD

**Issue by prockenschaub** [mlr-org/mlr3pipelines#284]
When `PipeOpLearner` is the final node in a GraphLearner, I would have expected the GraphLearner to use the same `predict_type` as the `PipeOpLearner`. This does not seem to be the case (see reproducible example below). Is there a possibility/wish to detect this automatically?

```r
library(mlr3)
library(mlr3pipelines)

# Get an example task
task = tsk("german_credit")

# Construct the learner, once with only specifying the predict_type 
# in the learner and once also specifying it in the GraphLearner
lrn = lrn("classif.rpart", predict_type = "prob")
po = po("scale")

graph_sugar = po %>>% lrn
graph_constructor = GraphLearner$new(po %>>% lrn, predict_type = "prob")

msr = msr("classif.auc")

# Try to obtain AUC which requires predict_type = "prob"
graph_sugar$train(task)
msr$score(graph_sugar$predict(task))
# NaN 
# (if resampling and aggreate are used, this throws
# Error: Measure 'classif.auc' needs predict_type 'prob')

graph_constructor$train(task)
msr$score(graph_constructor$predict(task))
# 0.7805095
```

**Comment by prockenschaub** [comment]
Potentially related to the bug mentioned in #264

**Comment by mllg** [comment]
I talked to @mb706 about this. IIRC, he said that it is not always possible to automatically determine the predict type. However, we agreed that a simple heuristic could be implemented which should work in almost all use cases.

**Comment by mb706** [comment]
This is a good issue, but moving the discussion over to https://github.com/mlr-org/mlr3pipelines/issues/306 because this is the duplicate I happened to respond to.
