### ISSUE TITLE
$importance() for graphlearner

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#291]
when prepending a learner with some preprocessing we still might need to access the learner's $importance

**Comment by mb706** [comment]
This is easy when only one learner is encapsulated, but what if
- Multiple learners are encapsulated
- Something else that credibly gives some importance measure is encapsulated, e.g. a filter

Possible solution: the GraphLearner gets some extra hyperparameter "which.importance" with levels = all `PipeOp`s that have an `$importance` slot. The `PipeOpLearner(CV)` would need to have an importance slot whenever what the encapsulate has one (how can this be done during construction?), and other PipeOps can also have `$importance` slots in principle.

**Comment by xhxlilium** [comment]
I don't know whether you have fixed it, as I still face the same problem. Any suggestion?
