### ISSUE TITLE
virtual greplicate

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#293]
Maybe it would be possible without much pain to get bagging to work from the Graph itself by introducing some kind of do-the-following-multiple-times PipeOp, and another PipeOp that then collects the multiple outputs; this would require some adjustments to the Graph similar to PipeOp(Un)Branch.

**Comment by mb706** [comment]
This would also be usefuul for one-vs-rest classification. What we want is that  a part of the graph is evaluated a number of times not yet specified at construction.

## This is how we do it:

1. Currently the edges of our graph only carry either NO_OP-Tokens or data. NO_OP-Tokens lead to a `PipeOp` ignoring the value, and data is just given to the `.train()` and `.predict()` function. I am introducing a new concept: **multiplicities**: they are named or unnamed lists of data, tagged with a class or whatever indicating that they are multiplicities. (In a sane world they would be S3 objects, just like the NO_OP-token would be).
2. `PipeOp`s can be either "multiplicity-aware" or "multiplicity-agnostic". Just like most `PipeOp`s are NO_OP-agnostic (only PipeOpBranch and PipeOpUnbranch are not), most `PipeOp`s are multiplicity-agnostic, i.e. they are not changed explicitly to handle multiplicities in a special way.
3. If a Multiplicity-agnostic `PipeOp` receives a multiplicity input, the `PipeOp` base class `train()` and `predict()` functions react to it the following way:
    * **`train()`**: the `self$train()` function itself is called recursively multiple times in a loop, once for each element of the multiplicity. after each call, the `$state` is saved in an accumulator and `$state` is reset to `NULL`. After this loop, the `$state` is set to an unnamed / named list (depending on if the multiplicity was named) of the individual `$state` values. The output value is a multiplicity with same names / lengths as the input value was.
    * **`predict()`**: after checking that the incoming value is a multiplicity with same length / names as `$state`, the `self$predict()` function is called recursively in a loop for each element of the multiplicity. For each call, the `$state` is set to each element of the original `$state` corresponding to the element of the multiplicity being evaluated. Afterwards, the `$state` is reset (with `on.exit()`). The output value is a multiplicity with same names / lengths as the input value was.
    * If a `PipeOp` has multiple inputs and only some of them are multiplicities, then the non-multiplicity inputs are "promoted" to multiplicities of same length / names.
    * If a `PipeOp` has multiple inputs and some of them are multiplicities with *differing names or lengths* an error is thrown (because I'm too lazy / incompetent to come up with some automatic-cartesian-product scheme that still makes sense in corner cases within 30 seconds right now).
    * Note that the recursive calls of `self$train()` / `self$predict()` (I am using these and not `private$.train()` / `private$.predict()` on purpose here!) enable us to trivially have "nested" multiplicities!
4. Multiplicity-Aware `PipeOp`s can either *emit* multiplicities or *collect* multiplicities. This is indicated by the input / output types in the `$input` and `$output` tables being surrounded by `[` `]`. E.g. a `PipeOp` emitting multiplicities of `Task` has `$output` type `"[Task]"` instead of `"Task"` etc. Not all input / output channels of a `PipeOp` need to have this at the same time. We call the `PipeOp`s that *do* have this "multiplicity emitting channels" / "multiplicity collecting channels". A channel must have `[` `]` types for *both* training *and* prediction, or *none* of them.
    * **Multiplicity emitting** `PipeOp`s just return a `Multiplicity(t1, t2, t3, ...)` object as one of their outputs instead of the normal output. The type of this can still be checked inside the `self$train()` / `self$predict()` function, just like currently the type conformity of `private$.train()` / `private$.predict()` are checked.
    * **Multiplicity collecting** `PipeOp`s expect a multiplicity input. If the input is not a nested multiplicity, then instead of going through the `self$train()` / `self$predict()` recursive call loop, the value is just given to the `private$.train()` / `private$.predict()` function that expects the multiplicity.

        If the input is a nested multiplicity, then the outer nesting layer is looped through recursively as usual, only the deepest nestinglayer "collected", i.e. passed on to `private$.train()` / `private$.predict()`.
5. All `PipeOp`s that currently have a "vararg" input channel (name `...`) get a construction argument "`collect`" (default `FALSE`) that instead turns the `...` channel into a multiplicity collecting channel. This way we get e.g. a `PipeOpFeatureUnion` that just collects all `Task`s in a multiplicity and `cbind`s them.

## Examples / What does this get us?

* **`PipeOpReplicate`**: single input channel of type `*`, single output channel of type `[*]`. Single integer parameter `reps`. It just does
    ```r
    .train = function(inputs) {
      list(do.call(Multiplicity, rep(list(inputs), self$param_set$values$reps))
    },
    .predict = function(inputs) {
      list(do.call(Multiplicity, rep(list(inputs, self$param_set$values$reps))
    }
    ```
    Here the input is copied `reps` times so that the following `PipeOp`s are executed `reps` times. Bagging with variable number of bags would look like the following:
    ```r
    po("replicate") %>>% po("subsample") %>>% lrn("classif.rpart") %>>%
      po("classifavg", collect = TRUE)  # the vararg channel collects multiplicity 
    ```
    The `replicate.reps` parameter would control the number of bagging iterations that are performed.
* **One vs. Rest classification**: Use a `PipeOpOVRSplit` with input `TaskClassif` and output `[TaskClassif]`. Use a `PipeOpOVRUnite` with input `[Prediction]` and output `Prediction`. The `[TaskClassif]` output contains a multiplicity of binary tasks that each contain a different split of one-class-vs-the-rest targets. The following `PipeOpLearner` (or also entire graph) sees each of these tasks individually and predicts individually. the `PipeOpOVRUnite` then compiles a multiclass prediction from the binary predictions. Example usage:
    ```r
    po("ovrsplit") %>>% lrn("classif.rpart") %>>% po("ovrunite")
    ```
* **Helper `PipeOp`s**: We want to have a `PipeOp` that makes multiplicities "explicit" in the graph structure (explicate): Take a multiplicity as input and have *N* output channels. We also want the reverse: a `PipeOp` with vararg / fixed number of input channels that collects the input to a multiplicity (make it implicit). For this we have
    * **`PipeOpExplicateMultiplicity`**: input type `[*]`, output type `c("*", "*", "*", ...)` as many times as construction argument `outnum`
    * **`PipeOpImplicateMultiplicity`**: input type `*` (vararg) or `c("*", "*", "*", ...)` (as many times as construction argument `innum`), output type `[*]`

**Comment by pfistfl** [comment]
I am trying to note down my first thoughts on this, and will get back to you when I thought about it more in-depth:
- In general, I like the concept. it makes graph's slimmer and would reduce complexity at least in a few situations.
- It gives us a lot more freedom, as we do not have to specify the number of input's / output's on graph construction anymore which was already problematic in some cases.

I can think of the following **cons**:
- I guess this concept is not easy to communicate/understand to the average user. The execution now does not match what we'd visually expect when looking at e.g. a plot of the graph any more, as some paths are executed multiple times.
- This would introduce another layer of parallelism, and make parallelization more complex, as what you describe is basically sequential (if accumulation order matters). I guess this might not be such a big issue in most cases and could be circumvented.

**one-vs-rest**
One problem here is, that in many such cases, we would also like to have the original labels/factor levels and somehow drag them along to the "collector" node, as they get lost in the binarization. (This is even more of a problem e.g. in ordinal classification). In the ordinal design, we basically had an additional connection from task -> collector which was just there to transport the labels.


All in all, I am in favor of doing this, but at the same time, I would perhaps put this on the agenda after we submit the current version (and perhaps also caching)?

**Comment by mb706** [comment]
> the original labels/factor levels and somehow drag them along

we could just have them in the positive classes of each binary task, i.e. setosa vs rest, versicolor vs. rest, virginica vs rest --> setosa, versicolor, virginica. Or as the names of the multiplicities. The ordering of elements in multiplicities stays the same, so ordered outcomes would not be a problem.

**Comment by mb706** [comment]
OVR is now also in the PR. 
## Further Discussion --> #443
