### ISSUE TITLE
Learner should be saved with it's model

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#297]
Not entirely sure how we want to solve this, but things currently are
 a bit inconsistent between mlr3 and mlr3pipelines.

**Use-Case:**
My learner defines a `plot` method that can be used after training.
I would basically use `learner$train(task); learner$plot()` to call the plot after training. 
This works fine for standard mlr3 learners.
Internally the plot function would do something like 
```
plot = function() plot(self$model)
```

If I now use this with pipelines, the `model` is not saved inside the learner, but inside the pipeop's state.
This would mean that all methods defined inside the learner do no longer work?

**Example**

```r
library(mlr3pipelines)
polrn = PipeOpLearner$new(lrn("classif.rpart"))
polrn$train(list(mlr_tasks$get("iris")))
polrn$state$model
polrn$learner$model
```

>  polrn$state$model
> n= 150 node), split, n, loss, yval, (yprob)
>      * denotes terminal node
> ...

> polrn$learner$model
NULL

**Comment by mb706** [comment]
The reason the `$learner` model is not set is that a PipeOp should only modify its `$state` during training, nothing else. We could turn `$learner` into an active binding that gets the learner model from the `$state`.

**Comment by pfistfl** [comment]
I guess that would work, and I would guess it might even be necessary, to keep the learner structure consistent in pipelines?

Any comments @berndbischl @mllg?

**Comment by mb706** [comment]
Reminder for myself: 
> turn $learner into an active binding that gets the learner model from the $state.
