### ISSUE TITLE
Feature Request: vtreat for mlr3pipelines

### ISSUE THREAD

**Issue by AtharKharal** [mlr-org/mlr3pipelines#300]
Is it possible that the statistically sound dataframe conditioner package 'vtreat'  (https://winvector.github.io/vtreat/index.html) is appropriated in mlr3piplines, because vtreat has certain very nice functionalities for an automatic and fast data preparation workflow.

**Comment by AtharKharal** [comment]
An "inverse" function may be envisioned which spits all the intermediary pipeops through which a vtreat treatment has been, or may be, reached. Such an auto-generated pipeline will allow further tweaking while at the same time taking advantage of the expertise of vtreat.

**Comment by pfistfl** [comment]
Hey @AtharKharal,

Thanks for the suggestion.
I think we already implemented some of the methods described in `vtreat`. 

I think it would be really cool to have all the others. 
Could you make a list of things you would deem most important? 

It might take a while for us to get around to implement this, but it might definitely be an option.
