### ISSUE TITLE
ParamSet$deps for branching operators.

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#304]
In `https://github.com/mlr-org/mlr3book/issues/116`,  a branching mechanism is used to tune over different filters.
- Currently, the `$deps` of the `ParamSet` do not correctly reflect that some params depend on the `branching` param chosen. This should be automatically added upon construction.
- It is also very cumbersome to specify the dependency graph by hand when constructing a `ParamSet` for tuning. There should be a mechanism like 
`tune_ps$deps = c(tune_ps$deps, graph_learner$deps)` that lets us automatically add the dependencies.

**Comment by mb706** [comment]
Closing as duplicate of https://github.com/mlr-org/mlr3pipelines/issues/101. This is definitely an important issues, and I am pretty sure I know how to do this well, but paradox currently blocks us on that. Please continue discussion in the linked issue.
