### ISSUE TITLE
Tag PipeOp Category

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#305]
Similar to https://docs.microsoft.com/de-de/dotnet/machine-learning/resources/transforms

**Comment by pfistfl** [comment]
Can this be `auto-generated` from `mlr_pipeops` ?

**Comment by pfistfl** [comment]
Proposal: 
We tag every `PipeOp` while adding it to the dictionary with a `category`, examples: See link above.

This allows us to auto-generate tables for the book/documentation.

Opinions? 
@mb706

**Comment by pfistfl** [comment]
I will try to come up with a list of `tags`: 
- [ ] Meta: Branch / Unbranch / Copy / gunion / ...
- [ ] Missings
- [ ] Feature Selection
- [ ] Imbalanced Data
- [ ] Data Transform
  - [ ] Scaling
  - [ ] Mutation
  - [ ] Transform
- [ ] Special Feature Types
  - [ ] Categoricals
  - [ ] Date Features
  - [ ] Text Features
- [ ] Target Transform
- [ ] Ensembling

**Comment by mllg** [comment]
I'd like to have such a structure.

**Comment by berndbischl** [comment]
Want it too

**Comment by pfistfl** [comment]
Should `tags` live in the dictionary or in the `pipeop`?

**Comment by mb706** [comment]
PipeOp, so inheritance is automatic.

**Comment by mb706** [comment]
Argument against it would be that it forces us to construct the pipeop for inspection, but the dictionary already does this for `as.data.table`

**Comment by mb706** [comment]
I already had some tags in mlrCPO: [link](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_3_all_CPOs.html).
The challenge is to come up with meaningful categories.

**Comment by pfistfl** [comment]
I guess we can have multiple, in order to be more open.

1. So is the decision, that we add `tags` as a slot to the `PipeOp`?

2. Should all `abstract` po's get the `abstract` `tag` ?

**Comment by mb706** [comment]
My first instinct would be to give the abstract pipeops the tags of the concrete pipeops if possible. e.g. if we end up having an "Ensembling" tag, the (abstract) PipeOpEnsemble should have this tag, then the inheriting PipeOps don't need to add it explicitly.

**Comment by mb706** [comment]
(Inheriting pipeops would still have the option to overwrite tags, of course)

**Comment by mb706** [comment]
This is now the "tag pipeop by category" issue, the "list implemented pipeops in documentation" issue is https://github.com/mlr-org/mlr3pipelines/issues/214.

**Comment by pfistfl** [comment]
See #324

**Comment by pfistfl** [comment]
Fixed via #324
