### ISSUE TITLE
Use selectors in select_cols 

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#320]
PipeOps inheriting from PipeOpTaskPreproc(Simple) and overloading the `_dt` functions (e.g. predict_dt, transform_dt) can select the columns they operate on. E.g. PipeOpEncode
```r
select_cols = function(task) {
  task$feature_types[get("type") %in% c("factor", "ordered"), get("id")]
}
```
This selects the features by type. However, we have a shortcut for this now:
```r
select_cols = selector_type(c("factor", "ordered"))
```

To Do:

1. Replace a single select_cols with a `selector_type()` and see if tests still pass. If they don't, get back to me. I hope the tests pass, then just continue.
2. Search for all `select_cols` occurrences in mlr3pipelines and replace them with the fitting `selector_...()` functions. Make sure the correct types are used. There are also some occurrences of
    ```r
    select_cols = function(task) task$feature_names
    ```
    replace those with
    ```r
    select_cols = selector_all()
    ```

**Comment by mb706** [comment]
Please wait until https://github.com/mlr-org/mlr3pipelines/pull/324 is merged before starting this.

**Comment by pfistfl** [comment]
`PipeOpTaskPreproc` and friends are solved centrally via `feature_types`, added selectors for `PipeOpImpute`  and friends.
