### ISSUE TITLE
PipeOp for target preprocessing

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#322]
We want to do things to the task that can be inverted later. This can be simple target operations ([see TOCPO](https://cran.r-project.org/web/packages/mlrCPO/vignettes/z_4_custom_CPOs_terse.html#makecpotargetop)), or more complicated stuff. The issues we have that would profit from this are  https://github.com/mlr-org/mlr3pipelines/issues/183, https://github.com/mlr-org/mlr3pipelines/issues/189, maybe https://github.com/mlr-org/mlr3pipelines/issues/301(?). @pfistfl idea was to write a single generic inverter PipeOp that does something to a Prediction / to multiple Predictions, and that whatever happens is determined by an inverter function that is sent along a channel.

We should probably write a class that facilitates easy generation of the inverter function. The user should overload a train(), a predict(), and an invert() function, and the class takes care of generating the function that is sent along the edge to the inverter PipeOp. This is similar to how PipeOpTaskPreproc operates, and maybe this can even be tacked on to PipeOpTaskPreproc. The only issue here is that PipeOpTaskPreproc is for a single task output, while our TOCPO may want to generate multiple tasks that are then put back together by the inverter.

PipeOps to write:
* [x] PipeOpInvert
* [x] PipeOpInvertiblePreproc. Or maybe put this together with PipeOpTaskPreproc, not sure.

**Comment by sumny** [comment]
#364

**Comment by pfistfl** [comment]
po_ytrafo %>>% ... graph  .... %>>% po_ytrafoinverter
          \ -----------------------------------------------/

po_ytrafo = Abstract;
Slots:
 trafo():  e.g. log
invert(): e.g. exp
state (e.g. scaling factors)

po_ytrafo_log; sets trafo = log; invert = exp

**Comment by pfistfl** [comment]
Same as #364, closing here.
