### ISSUE TITLE
check `affect_columns` result for correct type.

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#327]
A user using the wrong `affect_columns` function as in https://github.com/mlr-org/mlr3pipelines/issues/325 should give an error message.

Modify `PipeOpTaskPreproc.R` and check the result of the line
```r
affected_cols = self$param_set$values$affect_columns(intask)
```
with `assert_subset(affected_cols, intask$feature_names)`. Write a test that giving the wrong function as in #325 actually throws an error now.

**Comment by pfistfl** [comment]
Taken care of in #323
