### ISSUE TITLE
Selector for factorials by cardinality

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#330]
[This selector](https://github.com/mb706/autoxgboost3/blob/41f3523582792fd332be1a2340ff6e24bfd2562d/R/autoxgboost.R#L162-L168) could be generally useful. I suggest the following changes
* Rename to `selector_cardinality_greater_than`
* Select names where there are *more* levels than given: `levlens > levels`
* Parentheses different in the last line: `names(levlens)[levlens > levels]
* Maybe there is a way to do this without cloning, e.g. by sapplying a `length(distinct_values(x))` on all factorial / logical(?) columns

Prepare this selector in `Selector.R`, see first paragraph in https://github.com/mlr-org/mlr3pipelines/issues/326 how to do that. (I am the original author of autoxgboost3 and I'm granting the necessary license rights for that etc.)

**Comment by pfistfl** [comment]
I did not go deeper into avoiding cloning; would assume that the computational cost does not drastically differ. If you disagree, let me know.

**Comment by mb706** [comment]
I guess it's fine, it probably won't be a hotspot

**Comment by mb706** [comment]
closed by  #406
