### ISSUE TITLE
Missing PipeOp: CountVectorizer (sklearn)

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3pipelines#332]
#283

**Comment by pfistfl** [comment]
I will write down the todo's here and link here from all other related issues.

1. This PipeOp deals with `text` features. I would suggest, we assume that all of those features are  of type `character`. Therefore the po would only operate on character columns.

1. We need to find a good package that can possibly do all of the transforms required here, i.e.
  tokenization / stop-word-removal / tf-idf trafo / ngram-trafo / optionally word2vec.

  The first step would thus be:
  Search through https://cran.r-project.org/web/views/NaturalLanguageProcessing.html
  for a package that suits our purposes:
  - Actively Developed
  - On CRAN
  - Good Performance, low memory overhead, not calling java code etc.
  - Optionally: Developed on Github, Has Unit-tests and CI
  - Introduces few dependencies
  - Can do all / most of the transforms mentioned above.
 
  A first `Contrib` work would thus be to propose relevant  packages to enable discussion on a 
  framework to use.

**Comment by pfistfl** [comment]
I collected some more info on viable options:

* **tidytext**: (https://cran.r-project.org/web/packages/tidytext/vignettes/tidytext.html)
   * Has all the functionality we need (tokens, n-grams, tf-idf, stop-words), works for different
     text type (txt, html, ...) 
   * Imports dplyr and friends 
   * internally relies on `hunspell`, `tokenizers`, `stopwords`

* **cleanNLP**: (https://github.com/statsmaths/cleanNLP)
  * No dependencies
  * stringi as backend / + additional optional R / python backends 
  *  Can do everything we want in combination with [NLP](https://cran.r-project.org/web/packages/NLP/index.html) (again, no dependencies)

Others: 

* **spacyr**
  Interface to spacy via reticulate, requires python

**Comment by pfistfl** [comment]
Solved in #365
