### ISSUE TITLE
Missing PipeOp: Imputation via kNN

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3pipelines#342]
#254 See https://github.com/tidymodels/recipes/blob/master/R/knn_imp.R

**Comment by pfistfl** [comment]
This should also be covered in #386, closing here

**Comment by py9mrg** [comment]
This doesn't seem to work for me (but it's not impossible I'm doing something stupid). Using the example code in the [documentation](https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_imputelearner.html):

```
library("mlr3")

task = tsk("pima")
task$missings()
#> diabetes      age  glucose  insulin     mass pedigree pregnant pressure 
#>        0        0        5      374       11        0        0       35 
#>  triceps 
#>      227 

po = po("imputelearner", lrn("regr.rpart"))
new_task = po$train(list(task = task))[[1]]
new_task$missings()
```

But changing the learner to knn:

```
library("mlr3")

task = tsk("pima")
task$missings()
#> diabetes      age  glucose  insulin     mass pedigree pregnant pressure 
#>        0        0        5      374       11        0        0       35 
#>  triceps 
#>      227 

po = po("imputelearner", lrn("regr.kknn"))
new_task = po$train(list(task = task))[[1]]
new_task$missings()
```

Gives me the following error (penultimate line):

```
Error in check_prediction_data.PredictionDataRegr(pdata) : 
  Assertion on 'pdata$response' failed: Must have length 5, but has length 1.
```

It's not a disaster as I can use `PipeOpVIM_kNN` from NADIA, as per:

```
library("mlr3verse")
library("NADIA")
# Task with missing data from mlr3
task_with_missing <- tsk('pima')

# Creating an operator implementing the imputation method
imputation_methods <- PipeOpVIM_kNN$new()

# Imputation
task_with_no_missing <- imputation_methods$train(list(task_with_missing))[[1]]

#Check

task_with_missing$missings()

task_with_no_missing$missings()
```

But just thought I'd mention it.

**Comment by mb706** [comment]
I think you run into the problem that kknn itself doesn't like missing values and gives an error when it is queried to do imputation (the error message is admittedly bad: https://github.com/mlr-org/mlr3learners/issues/175). 

```r
po = po("imputelearner", po("imputehist") %>>% lrn("regr.kknn"))
```
should work instead.

**Comment by mb706** [comment]
Opened an issue about documenting this: https://github.com/mlr-org/mlr3pipelines/issues/564

**Comment by mb706** [comment]
Thanks for reporting @py9mrg!

**Comment by py9mrg** [comment]
You're absolutely right - that's sorted it. Thanks so much.

And you're very welcome!
