### ISSUE TITLE
PipeOpTuneThreshold

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#351]
Should set the threshold after a PipeOpLearnerCV. This is different from https://github.com/mlr-org/mlr3pipelines/issues/350. See discussion here: https://github.com/mlr-org/mlr3pipelines/issues/59.

**Comment by pfistfl** [comment]
This already exists in #152 
I will do a refactoring and then create a new PR.

**Comment by mb706** [comment]
Closed by https://github.com/mlr-org/mlr3pipelines/pull/152
