### ISSUE TITLE
Nested Resampling with LearnerCV

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#357]
The following currently fails: 

```r
test_that("PipeOpLearnerCV - within resampling", {
  lrn = mlr_learners$get("classif.rpart")
  gr = GraphLearner$new(PipeOpLearnerCV$new(lrn) %>>% po(id = "l2", lrn))
  resample(tsk("iris"), gr, rsmp("holdout"))
})
```

reason: `task_cbind()` checks for identity of backend row_ids (150 rows) and cv-train-data during resampling (~110 rows). 

I guess this is a problem within `mlr3`. @mllg

**Comment by pfistfl** [comment]
Seems to be a result of https://github.com/mlr-org/mlr3/issues/423

**Comment by mllg** [comment]
Should be fixed now. Can you test it?

**Comment by pfistfl** [comment]
is fixed, thank you! I added a test.
