### ISSUE TITLE
traverseGraph should potentially be a method of Graph. it also should be called "map"

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#36]

**Comment by zzawadz** [comment]
https://github.com/mlr-org/mlr3pipelines/commit/e5b5bdeb1d827b4bbc0434b2edc1201df0c283d6 - new map function.

**Comment by berndbischl** [comment]
thx. but pleeeeease no simplify = TRUE. at least not as the default.

**Comment by berndbischl** [comment]
obsolete
