### ISSUE TITLE
[Question] How to deal with different preprocessing steps as hyperparameters

### ISSUE THREAD

**Issue by statist-bhfz** [mlr-org/mlr3pipelines#362]
I'm looking for convenient way to deal with different preprocessing steps as hyperparameters.
I understand that particular transformations like PCA are parameterized and so can be tuned like any other learner. But what should I do to compare models with `imputemean` and `imputemedian`? Is it necessary to create two branches in learning graph (first with learner using mean imputation and second with  another one using median imputation), as described in https://mlr3gallery.mlr-org.com/tuning-over-multiple-learners/?

With `recipes` desirable functionality can be implemented as
```
create_recipe <- function(data = train_data,
                          imp_strategy = "mean_imp", 
                          n_bins = 3) {
 
  imp_methods <- list(mean_imp = step_meanimpute, 
                      median_imp = step_medianimpute)

  rec_obj <- recipe(churn ~ ., data = data) %>%
    imp_methods[[imp_strategy]](one_of(num_columns)) %>%
  ...
```

**Comment by pfistfl** [comment]
the idea is to either use branching as you mentioned or at a future point `PipeOpProxy` (see #349).
I am working on providing sugar for the branching/unbranching mechanism (in #361), but this for now leads to problems in the dependencies introduced in the `ParamSet` and is therefore not available yet.

In the future, you would then have to specify something like 
```r
ppl("branching", list(po("imputemean"), po("imputemedian"))) 
```
in order to create the `branch -> gunion -> unbranch` flow.

This would then still require you to tune over the `branching`  param.
I guess this is also true for the `tidyverse`?

**Comment by statist-bhfz** [comment]
@pfistfl Yes, tuning across `branching` parameter is exactly the thing. Using branches without `gunion -> unbranch` steps and without tuning mechanism will result in as many terminal nodes as preprocessing options are checked (this is undesirable solution). `PipeOpProxy` also looks like valid alternative if it will be implemented as described.

`tidyverse` approach consists in explicit looping across manually created hyperparameters grid, e.g.
```
param_grid <- expand.grid(imp_strategy = c("mean_imp", "median_imp"),
                          n_bins = c(2, 3), 
                          alpha = c(0, 0.5, 1),
                          lambda = c(0.1, 0.01, 0.001)
                          )

across_grid <- function(split, grid) {
  metrics <- lapply(seq_len(nrow(grid)),
                    function(i) logreg_fit_pred(split, 
                                                data = train_data,
                                                grid[i, "imp_strategy"],
                                                grid[i, "n_bins"],
                                                grid[i, "lambda"],
                                                grid[i, "alpha"]))
  result <- do.call(rbind, metrics)
  return(cbind(grid, result))
}
```
This is an example of simultaneous tuning of two `glmmet` parameters (`lambda`, `alpha`), one prepocessing step parameter (`n_bins` for `step_discretize()`) and one alternative between different prepocessing steps (`imp_strategy` switches between `step_meanimpute()` and `step_medianimpute`). 
It is flexible, but I'm not very happy with writing and debugging such amount of code. `mlr3` seems much more handy for complex ML pipelines.

**Comment by pfistfl** [comment]
Doesn't  [tidymodels](https://tidymodels.github.io/tune/articles/grid.html)  have the `tune()` thing? 
I actually liked that idea in terms of API design.

In `mlr3` you can always do the same, i.e. just create two different graphs and evaluate all graphs.

The code in https://github.com/mlr-org/mlr3pipelines/pull/361/files for `branch_pipeline` should already work for `add_deps` = FALSE. 
You would then just have to add the dependencies manually until we find a better solution.

**Comment by statist-bhfz** [comment]
Unfortunately, `tune`  from `tidymodels` allows to tune parameters of the model as well as for preprocessing steps (I missed this functionality earlier) but still doesn't provide interface for switching between steps:
```
ames_rec <- 
  recipe(Sale_Price ~ Longitude + Latitude, data = ames_train) %>% 
  step_log(Sale_Price, base = 10) %>% 
  step_ns(Longitude, deg_free = tune("long df")) %>% 
  step_ns(Latitude,  deg_free = tune("lat df"))
```
helps to select right parameters for natural splines (`step_ns()`), but what if we want to compare models with and without such feature engineering? It is possible to perform two different tuning procedures. However, everything gets much worse with more complex pipeline. For example, we need 4x3x4=48 tuning procedures to check 4 imputation methods, 3 scaling methods for numeric features and 4 encoding methods for factors.

**Comment by statist-bhfz** [comment]
@pfistfl I tried to fix your code from https://github.com/mlr-org/mlr3pipelines/pull/361/files 
```
    pmap(list(graphs, nms), function(graph, id) {
      map(graph$param_set$ids(), function(par) {
        gr$param_set$add_dep(par, "branch.selection", CondEqual$new(id))
      })
```
My solution:
```
pmap(list(graphs, mlr3misc::map(graphs, "id")), function(graph, id) {
  graph$param_set$add(ParamFct$new("branch.selection", 
                                   levels = unlist(mlr3misc::map(lrns, "id"))))
  map(setdiff(graph$param_set$ids(), "branch.selection"), function(par) {
    graph$param_set$add_dep(par, "branch.selection", CondEqual$new(id))
  })
})
```

**Comment by statist-bhfz** [comment]
@pfistfl I tried to fix your code from https://github.com/mlr-org/mlr3pipelines/pull/361/files 
```
pmap(list(graphs, nms), function(graph, id) {
  map(graph$param_set$ids(), function(par) {
    gr$param_set$add_dep(par, "branch.selection", CondEqual$new(id))
  })
})
  ```
My solution:
  ```
pmap(list(graphs, mlr3misc::map(graphs, "id")), function(graph, id) {
  map(graph$param_set$ids(), function(par) {
    gr$param_set$add_dep(paste(id, par, sep = "."), 
                         "branch.selection", 
                         CondEqual$new(id))
  })
})
  ```
  Please check it, maybe I missed something.

**Comment by pfistfl** [comment]
If I saw it correctly, the problem was not the code per se, but instead that in some cases, the set values (i.e. `xvar = 0` for rpart) do not allow to change the parameter value. 
(Hence why the learner can not be set to `classif.featureless` in the example.

This is an issue downstream and needs to be fixed in `paradox`.

Thanks for the effort though!

**Comment by statist-bhfz** [comment]
Sorry, my wrong. I thought it is mismatching between ids in `graph$param_set` and `gr$param_set`, but `minsplit` in pipeop becomes `classif.rpart.minsplit` after applying `as_graph()`.

**Comment by statist-bhfz** [comment]
However, tuning procedure works great with current realisation. I just switched task to `"sonar"` and used some code from https://mlr3gallery.mlr-org.com/tuning-over-multiple-learners/
```
library(mlr3)
library(mlr3misc)
library(mlr3tuning)
library(mlr3pipelines)
library(mlr3learners)
library(paradox)
library(checkmate)

branch_pipeline = function(graphs, add_deps = TRUE) {
  graphs = map(graphs, as_graph)
  nms = names(graphs)
  if (is.null(nms)) 
    nms = map_chr(graphs, function(x) str_collapse(map_chr(x$pipeops, "id"), sep = "."))
  gr = po("branch", nms) %>>% gunion(graphs) %>>% po("unbranch")
  # Iterate over all graphs and add dependencies on branch.selection
  # FIXME: This forbids to set some values, see example above.
  #        Changes to paradox might be required here.
  if (assert_flag(add_deps))
    pmap(list(graphs, nms), function(graph, id) {
      map(graph$param_set$ids(), function(par) {
        gr$param_set$add_dep(par, "branch.selection", CondEqual$new(id))
      })
    })
  return(gr)
}

# mlr_graphs$add("branch", branch_pipeline)

lrns = map(list(lrn("classif.rpart"), lrn("classif.featureless")), po)
task = mlr_tasks$get("sonar")
gr = branch_pipeline(lrns, add_deps = T)
cv5 = rsmp("cv", folds = 5)
ps = ParamSet$new(list(
  ParamFct$new("branch.selection", 
               levels = c("classif.rpart", "classif.featureless"))
))

instance = TuningInstance$new(
  task = task,
  learner = gr,
  resampling = cv5,
  measures = msr("classif.ce"),
  param_set = ps,
  terminator = term("evals", n_evals = 20)
)

tuner = TunerRandomSearch$new()
tuner$tune(instance)
instance$result

resdf = instance$archive(unnest = "tune_x") 

resdf = tidyr::pivot_longer(
  resdf,
  "branch.selection",
  values_drop_na = TRUE)
library(ggplot2)
g = ggplot(resdf, aes(x = value, y = classif.ce))
g = g + geom_point()
g = g + facet_grid(~name, scales = "free")
g
```

**Comment by pfistfl** [comment]
yes, I think it will break if you also try to tune `rpart`s params.

**Comment by statist-bhfz** [comment]
Still works! (code is updated)

**Comment by berndbischl** [comment]
this is a super important issue. can we please mark this as high prio and discuss it during the workshop?

**Comment by berndbischl** [comment]
i want a convenient "idiom" for what the user requests here

**Comment by pfistfl** [comment]
There is an idiom, you can find in #361:

```r
ppl("branching", list(po("imputemean"), po("imputemedian"))) 
```

This is currently just blocked due to issues in `paradox`.

**Comment by berndbischl** [comment]
> This is c



> This is currently just blocked due to issues in `paradox`.

is there already a (minimal) issue in paradox? can you please link it here

**Comment by pfistfl** [comment]
These two issues kind of boil down to the same thing:
https://github.com/mlr-org/paradox/issues/240 & https://github.com/mlr-org/paradox/issues/216

**Comment by pfistfl** [comment]
Closing here, relevant issues + PR (#361) are open.
