### ISSUE TITLE
graphnode: setnext, etc should be defined internally

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#38]
not like this

    set_next = graph_node_set_next,
    set_prev = graph_node_set_prev,
    add_next = graph_node_add_next,
    add_prev = graph_node_add_prev,

**Comment by zzawadz** [comment]
Related: https://github.com/mlr-org/mlr3/issues/69

**Comment by berndbischl** [comment]
> Related: [mlr-org/mlr3#69](https://github.com/mlr-org/mlr3/issues/69)

i think this was answered, there. and we should simply do this and close

**Comment by berndbischl** [comment]
@mb706 refactored these anyway
