### ISSUE TITLE
out of range imputer

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#391]
should be named "PipeOpImputeOutOfRange", id "imputeoor". In mlr this was `imputeMin()` or `imputeMax()`. The imputed values should be something like
```r
max(x) + offset + multiplicator * diff(range(x))
```
with `max()` vs `min()`, `offset` and `multiplicator` a parameter defaulting to 1 both. The documentation should stress that this makes sense for tree-based methods and reference [this paper](http://www.jmlr.org/papers/volume11/ding10a/ding10a.pdf).

**Comment by berndbischl** [comment]
i think this should really be a part of PipeOpImputeNewLevel and not a new pipeop
