### ISSUE TITLE
handling of IDs in `ppl()`

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#393]
there should probably be aunified way to handle ID changes of pipeops introduced through `ppl()` / `mlr_graphs`.

**Comment by pfistfl** [comment]
Looking through currently existing `ppl`:
-  `robustify` does not have any, user could just make use of #403 if required
- `bagging` relies on `greplicate` below, does not need any
- `greplicate` should make use of #403 (`update_graph_ids`)
- `branching` currently has two different args which also need to behave differently from other use cases.

**Comment by mb706** [comment]
> user could just make use of #403 if required

I guess that is true in all cases. Let's see how well we like #403. I guess it would make the difference between
```r
x %>>% ppl("whatevs", id_prefix = "y") %>>% z
```
and
```r
x %>>% ppl("whatevs")$prefix_ids("y") %>>% z
```

**Comment by pfistfl** [comment]
PR in #409, we might either wanna use it or decide against it.

**Comment by pfistfl** [comment]
`$update_ids()`
