### ISSUE TITLE
maybe default po("missind") to only add indicator columns for numerics

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#395]
we usually impute factors with newlvl, so missinds are often not needed.

this would amount to setting `ps$values$affect_columns` in the constructor; would probably have to happen after the `super()` call in the constructor.

Opinions here? @pfistfl  @berndbischl

**Comment by pfistfl** [comment]
agree, taken up in #406

**Comment by mb706** [comment]
Closed by #406
