### ISSUE TITLE
Convenience function to prefix / postfix id's in a graph

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#398]
This is super cumbersome but often required to construct larger graph. 

Proposal:
```r
update_ids(graph, prefix = "", postfix = "")
```
This could be a member function in the graph.

Goes through all `PipeOp`s in a `Graph` pre/postfixes id's and returns new graph.

**Comment by mb706** [comment]
Good idea. Should be a member function of `Graph` imho.

See [greplicate](https://github.com/mlr-org/mlr3pipelines/blob/19f416e69b14e18c4c81cf0f836a1f4b53fd8c6c/R/greplicate.R#L20-L21) on how prefixing IDs works.

**Comment by pfistfl** [comment]
Fixed via ppl greplicate
