### ISSUE TITLE
we need a good printer for graphs

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#41]
1) the graphical plotter should plot the graph as is

2) the printer needs to show a compact form on the console.
we could implement this by topological sorting

with that i mean we sort the graph in layer. then show it like this:

[ids, 1] >> [ids, 3] >> [ids, 2]

the number is the number of elements in the layer, ids is a concatened string of the ids

**Comment by zzawadz** [comment]
Sth like this?

```
# Pipeline Graph
#  [(OpNULL), 1] >> [(scaler,pca), 2] >>
#  [(featureunion), 1] >> [(classif.rpart), 1] 
```

**Comment by pfistfl** [comment]
I like that.
The other option would be to make the printer have multiple lines which is a little tedious and not super important IMHO.

**Comment by berndbischl** [comment]
we need to figure out whther "layers" really exist in toposorting

**Comment by berndbischl** [comment]
how about we simply print the edge datatable, or its head? if the user wants to see the real graph, he plots it with igraph.

**Comment by mb706** [comment]
Currently the printer does this:
```r
> gr = PipeOpScale$new() %>>% PipeOpPCA$new() %>>% PipeOpLearner$new(mlr_learners$get("classif.rpart"))
> gr
Graph with 3 PipeOps:
             ID         State
1         scale <<UNTRAINED>>
2           pca <<UNTRAINED>>
3 classif.rpart <<UNTRAINED>>
> gr$train(mlr_tasks$get("iris"))
INFO [mlr3] Training learner 'classif.rpart' on task 'iris' ...
[[1]]
NULL

> gr
Graph with 3 PipeOps:
             ID        State
1         scale       <list>
2           pca     <prcomp>
3 classif.rpart <Experiment>
```

PipeOps are sorted topologically, but it is not limited to the head. Thoughts on this?

**Comment by berndbischl** [comment]
ok what you posted is something else, not the edges. but i still like it. check a bit, then colse

**Comment by berndbischl** [comment]
maybe we can add the predeccs and successors nodes as character cols?

**Comment by mb706** [comment]
Still needs predecessors & successors
