### ISSUE TITLE
check if pipeophistbin works correctly if not all bins are present

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#414]

**Comment by pfistfl** [comment]
I guess this would be solved by writing a unit test for this.

**Comment by ZackBarry** [comment]
I'd like to add a PR for this.  Just to clarify - is this the sequence of events that should be tested? 

1) A PipeOpHistBin is trained on Task1 , which has a value in (a,b]
2) The output from (1) does not contain (a,b]
3) The trained po is used for prediction on Task2, which has a value in (a,b]
4) The output from (3) contains (a,b]

**Comment by mb706** [comment]
Closed by https://github.com/mlr-org/mlr3pipelines/pull/372 (predict time value out of range) and #421 (predict time value in train-time-empty-bin)
