### ISSUE TITLE
gunion changes ids of passed pipeops if the list is named

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#419]
```
learns = list(
  foo = lrn("classif.ranger", id = "myrf"),
  bar = lrn("classif.rpart", id = "myrp")
)

g = gunion(learns)
print(g)
```

Results in
```
Graph with 2 PipeOps:
       ID         State sccssors prdcssors
 foo.myrf <<UNTRAINED>>
 bar.myrp <<UNTRAINED>>

```

At the very least that's not documented in ?gunion. 
I also don't like that prefixing, I think. The ID of PO in the resulting graph should be exactly as it was before?

**Comment by mb706** [comment]
> The ID of PO in the resulting graph should be exactly as it was before?

There is the option of leaving the list unnamed. Prefixing with names in a list is a neat way of avoiding ID collisions with little code and it is congruent with how `data.table()` works.
