### ISSUE TITLE
Renaming features: task$rename_features (moved from mlr3)

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#420]
Posted by @ZackBarry here (and moved by me):
https://github.com/mlr-org/mlr3/issues/268#issuecomment-623784752

----

Is it possible to use the task$rename() method within a pipeline? One use case that I haven't been able to find any solutions for is to union the results of two PCA branches. When I've tried this with gunion and mlr_pipeops_featureunion, only one set of PCX columns remains at the end of the graph. I'd like to be able to rename the output columns from the left PCA branch as "left_PCX" and the right branch as "right_PCX".

Toy example:
`library(mlr3)
library(mlr3pipelines)
library(dplyr)

toy_df <- data.frame(
homeWins = c(1, 0, 1, 0),
homeHits = c(13,10,12,11),
homeHomeRuns = c(0,2,0,0),
awayHits = c(10,11,14,8),
awayHomeRuns = c(1,0,1,1)
) %>%
mutate(homeWins = as.factor(homeWins))

task = TaskClassif$new("toy_task", backend = toy_df, target = "homeWins", positive = "1")

pca_home = po("select", id = "home_cols", param_vals = list(selector = selector_grep("home"))) %>>%
po("pca", id = "home_pca", param_vals = list(center = TRUE, scale. = TRUE))

pca_away = po("select", id = "away_cols", param_vals = list(selector = selector_grep("away"))) %>>%
po("pca", id = "away_pca", param_vals = list(center = TRUE, scale. = TRUE))

graph <- gunion(list(pca_home, pca_away)) %>>%
po("featureunion", id = "all_together")

graph$keep_results <- TRUE

graph$train(task)
#> $all_together.output
#> TaskClassif:toy_task (4 x 3)
#> * Target: homeWins
#> * Properties: twoclass
#> * Features (2):
#> - dbl (2): PC1, PC2`

**Comment by berndbischl** [comment]
@mb706 
Ok, I looked into this.

I think currently this is not (easily) possible, although you could EASILY create a local PipeOp that does this now. But we should support this out-of-the box to ensure flexible usage of the package

Options:

1) Allow a PipeOpRename type of op. 

2) Add a col-renaming function to the PipeOpPreproc-Task base class. 
(that would potentially rename cols after the preproc abstract method is called)

3) Let PipeOpColApply also handle that, maybe it already can. At least that's not documented.

4) Allow to pass prefix-strings for the feature columns in PipeOpFeatureUnion.
So like POFeatureUnion$new(prefixes = c("left", "right"))
So, assuming that this PO takes 2 input-tasks, all x-cols of the first one are prefixed with "left", the other ones with "right".

-----

Suggestions: 
I think I would allow 4) immediately, because it solves the direct usecase where this is probably needed the most, and its super-convenient for the user.
We also mention in the docs that an error occurs if colnames are non-unique - but no way how to deal with the problem (which is pretty much exactly the issue here)

Maybe we can allow also 1) to cover all other more exotic cases. 
2) and 3) feel a little bit less elegant, not sure though.

**Comment by sumny** [comment]
Regarding 4), this should already be possible, because `innum` also accepts a `character` `vector` which will result in "the number of input channels is the length of ‘innum’, and the columns of the result are prefixed with the values."

```
library(mlr3)
library(mlr3pipelines)
pop = po("featureunion", innum = c("left", "right"))
train_out = pop$train(list(tsk("iris"), tsk("iris")))[[1]]
train_out$feature_names
```

```
[1] "left.Petal.Length"  "left.Petal.Width"   "left.Sepal.Length" 
[4] "left.Sepal.Width"   "right.Petal.Length" "right.Petal.Width" 
[7] "right.Sepal.Length" "right.Sepal.Width" 
```

But I generally do like the idea of a `PipeOpRename`

**Comment by mb706** [comment]
As @sumny writes this was never a problem but we also have a `PipeOp` for things like this now.
