### ISSUE TITLE
PO TargetTrafo: Add example for mlr3

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#435]
My students struggled to construct a proper graph, an example might be useful.

**Comment by sumny** [comment]
I wrote a first version, mlr-org/mlr3gallery#57. sadly this needs new mlr3pipelines to hit CRAN to be correctly deployed. Anyone volunteering for review? (@berndbischl @mb706 @pfistfl @mllg). Also some more thoughts about what should be changed w.r.t. targettrafos can be found here mlr-org/mlr3pipelines#439

**Comment by sumny** [comment]
closed by https://mlr3gallery.mlr-org.com/posts/2020-06-15-target-transformations-via-pipelines/
