### ISSUE TITLE
PipeOpTextVectorizer: Add Sequence representation

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#436]
PipeOpTextVectorizer currently only allows returning a Bag-of-Words representation.
Many applications also work on a Sequence Representation  i.e.
 - represent tokens as integers
- output is a list of integer representations cut off after n tokens / padded up to n tokens

We should perhaps also give an option to do this.

**Comment by pfistfl** [comment]
This is implemented in #478 often required in e.g. `mlr3keras`

**Comment by mb706** [comment]
Closed by #478
