### ISSUE TITLE
PipeOpNull and PipeOpFeatureUnion can not be is_learnt

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#44]
`is_learnt` basically checks whether `private$.params` is set.

Methods that do not require `private$.params`, we might want to set this to 
`list()` or something?

**Comment by berndbischl** [comment]
actually i disagree here, PipeOpNULL can also be in a "learned" state. that simply means that information flowed through it. i mean, if the OP is in a graph, and data has flown through, we dont want some operators to be learned, and some not?

**Comment by berndbischl** [comment]
and if i get your proposal right, we simply ".params" in this case to a dummy value? which seem ok for me. 
I guess i would vote for "TRUE" than instead of "list()".
dunno. both could be fine for now. 

most important DOCUMENT THIS

**Comment by zzawadz** [comment]
So basically the `is_learnt` just checks if the train function has been called, and we should document it in this way:

```
`is_learnt` - determines if the function `train` has been called on that PipeOp.
```

Maybe `is_trained` will be less confusing?

**Comment by pfistfl** [comment]
Vote for calling it `is_trained`. Additionally, `.params`  can then be set to TRUE during training for such methods.

**Comment by pfistfl** [comment]
We set `self$state = list()`
-> Graph is now trained.
