### ISSUE TITLE
a Graph should have a deep copy method

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#45]

**Comment by berndbischl** [comment]
we should add a unit test that this works

**Comment by mb706** [comment]
Done [here](https://github.com/mlr-org/mlr3pipelines/blob/0bd21397ae6b1d43c7601937081d3ed0bd645f9a/tests/testthat/test_Graph.R#L44) using the new `expect_deep_clone()` helper function.
