### ISSUE TITLE
Support dot output for pipelines

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#458]
Would be nice to have for markdown. See https://github.com/yihui/knitr-examples/blob/master/057-engine-dot.Rmd for an example.

**Comment by sumny** [comment]
I am not 100% sure I fully understand how this should look. I.e. should we add an argument to the plot function to allow for dotted lines?

**Comment by mllg** [comment]
I want a Pipeline -> ASCII converter.

**Comment by sumny** [comment]
Fancy! I will try to provide a draft soon :+1:
