### ISSUE TITLE
as.data.table(mlr_pipeops) should not load packages

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#463]
otherwise it doesn't run when not all suggestions are installed

**Comment by mb706** [comment]
only seems to be a problem for the bag of words pipeop because it accesses some package in its paramset?

**Comment by pfistfl** [comment]
Yeah, I do this to get available options from the package IRC. I can also just hard-code this instead.

**Comment by pfistfl** [comment]
fixed in #478

**Comment by mb706** [comment]
Closed by https://github.com/mlr-org/mlr3pipelines/pull/478
