### ISSUE TITLE
PipeOpMultiplicityImply named 

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#472]
I guess we should allow for some sort of specifying names. 
Currently this is done via supplying a character vector to  `innum` 
but this simply returns "input1", ... instead of using the names specified in innum. 

Concretely, I would like to specify the names of the outgoing items.

**Comment by mb706** [comment]
Closed by 93c2f2648ef364dfda001f98e146531ac295fcfe
