### ISSUE TITLE
Do not directly access `$data` slots for RR/BMR/Prediction

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#475]
Result containers will be refactored soon (https://github.com/mlr-org/mlr3/pull/539). Instead of directly accessing the internal `$data` slot, the table must be created first via `as.data.table(obj)`. Let me know if this does not work for some pipeops.

I'll do the same for Prediction objects, please avoid accessing the `$data` slot here, too.

**Comment by sumny** [comment]
I locally tested mlr-org/mlr3#539 with the current mlr3pipelines master and everything seems to work fine.

For predictions, this may effect some target transformation `PipeOp`s but I can provide a fix soon.

**Comment by sumny** [comment]
closed by #499
