### ISSUE TITLE
Failures with dev testthat

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlr3pipelines#479]
When I run R CMD check on mlr3pipelines with dev testthat, I see a lot of failures like:

```
Training debug.multi with input list(input_1 = 1, input_2 = 1)
-- FAILURE (test_Graph.R:221:3): assert_graph test -----------------------------
Object addresses differ at path ROOT is not TRUE

`actual`:   FALSE
`expected`: TRUE 

-- FAILURE (test_Graph.R:221:3): assert_graph test -----------------------------
Object addresses differ at path ROOT is not NULL

`actual` is a character vector ('ROOT')
`expected` is NULL

-- FAILURE (test_Graph.R:221:3): assert_graph test -----------------------------
Object addresses differ at path ROOT->[element .__enclos_env__] '.__enclos_env__' is not TRUE

`actual`:   FALSE
`expected`: TRUE 
```

Would you mind helping me figure out what's gone wrong and whether this might be a bug in testthat?

**Comment by sumny** [comment]
Thanks for the issue report!

As far as I can tell these errors mostly seem to be simply caused by the change from the error message of, e.g., `expect_true` `isn't true.` --> `is not TRUE` and we do have some tests where we explicitly test against the error message by providing the `regexp` argument.

I fixed this here #480 and testing using testthat dev seems to pass fine!

**Comment by mb706** [comment]
Btw, what is happening here is that I have a function that verifies an assumption by firing some `expect_***()` calls. I call this function in a known-bad situation to make sure the expectations *do* fail when the assumption is not fulfilled.

What I actually need is to checks if one (of many) `expect_***()`s was triggered inside an expression, as I reported in https://github.com/r-lib/testthat/issues/839. `expect_failure()` doesn't work, so I have to use a fragile `expect_error()` with the error message to differentiate the expectation failure from actual errors happening for some reason.

**Comment by hadley** [comment]
To be clear, you're saying that you're using `expect_` functions to do input validation of function arguments?

**Comment by mb706** [comment]
I am using `expect_***()` inside a function that gets called during tests and that verifies an array of expectations about objects created by our code.

**Comment by hadley** [comment]
Would you mind providing a small example? Why are you wrapping those `expect_` functions inside of an `expect_error()` layer?

**Comment by mb706** [comment]
I think the following captures the essence of what we are doing. (Instead of "mostly equal" we test for "deep clone with no shared references" but that is not relevant here.) I want to make sure that `expect_stuff_mostly_equal` actually tests for something, and that that "something" (inequality / non-clone-ness) is triggered under the expected circumstances.

```r
# -- R/stuff.R
StuffClass = R6::R6Class("stuff",
  public = list(thing = NULL, another_thing = NULL, guid = NULL,
    initialize = function() self$guid <- runif(1),
    randomize = function() self$another_thing <- runif(1)
))

# -- tests/testthat/helper_functions.R
expect_stuff_mostly_equal <- function(left, right) {
  expect_equal(left$thing, right$thing)
  expect_equal(left$another_thing, right$another_thing)
}

# -- tests/testthat/test_stuff.R
context("stuff")
test_that("stuff works", {
  o1 <- StuffClass$new()
  o2 <- StuffClass$new()

  expect_stuff_mostly_equal(o1, o2)

  o1$randomize()
  o2$randomize()
  expect_expectation_fails(expect_stuff_mostly_equal(o1, o2))  # this is what we are doing here
})

**Comment by hadley** [comment]
I think you'd be better off with a pair of helper expectations:

```R
expect_stuff_mostly_equal <- function(left, right) {
  expect_equal(left$thing, right$thing)
  expect_equal(left$another_thing, right$another_thing)
}
expect_stuff_mostly_not_equal <- function(left, right) {
  expect_failure(expect_equal(left$thing, right$thing))
  expect_failure(expect_equal(left$another_thing, right$another_thing))
}
```

**Comment by hadley** [comment]
I'm now starting the testthat release process and I'm likely to submit to CRAN in one month.
