### ISSUE TITLE
Graph$source_node or Graph$source_nodes

### ISSUE THREAD

**Issue by zzawadz** [mlr-org/mlr3pipelines#51]
Right now `Graph` class can only have one source node. I'm not sure if we want to stick with this or do we want to change that to a list of nodes?

Right now we can't define a graph `list(a,b) %>>% c`. In such case we need to add a PipeOpNull at the beginning `PipeOpNull$new() %>>% list(a, b) %>>% c`. We could add a S3 method `%>>%.list`, which will create a graph with PipeOpNull at the beginning, but for me it would be a quite ugly solution.

**Comment by pfistfl** [comment]
What do we risk if the `Graph` accepts a list of Nodes?

**Comment by zzawadz** [comment]
I think nothing.

We would only need to support an API in which a user pass single task or list of tasks to the `train` function.
