### ISSUE TITLE
pipeline_robustify may create factors for learners which can't handle them

### ISSUE THREAD

**Issue by a-hanf** [mlr-org/mlr3pipelines#514]
Example:
```
library(mlr3)
library(mlr3learners)
library(mlr3pipelines)

task = tsk("pima")
model = GraphLearner$new(pipeline_robustify(task, lrn('classif.svm')) %>>% lrn('classif.svm'))
model$train(task)
```
Error: <TaskClassif:pima> has the following unsupported feature types: factor

The problem occurs because of "missind" pipeop. The indicators are stored as factors, even if the learner can not handle them. If factors_to_numeric evaluates to FALSE (for example if there are no factors present in the original dataset, like in the "pima" task), this can cause an error during training, because there will be factors without encoding.

**Comment by sumny** [comment]
Hi, nice catch and thanks for the bug report!
Kinda unlucky that we missed this. I linked a PR that should allow for a more adaptive selection of the type of the columns created by `PipeOpMissInd`.

**Comment by a-hanf** [comment]
Thanks for the fix. Unfortunately, this change broke something else. I am not sure why, but `pipeline_robustify` does not play nicely with learners from `mlr3learners.liblinear` any more. Some examples:
```
library(mlr3)
library(mlr3pipelines)
library(mlr3learners.liblinear)

pipeline = pipeline_robustify(tsk("iris"), lrn("classif.liblinearl1logreg"), impute_missings = TRUE) # breaks
pipeline = pipeline_robustify(tsk("iris"), lrn("classif.liblinearl1logreg")) # works

pipeline = pipeline_robustify(tsk("pima"), lrn("classif.liblinearl1logreg"), impute_missings = TRUE) # breaks
pipeline = pipeline_robustify(tsk("pima"), lrn("classif.liblinearl1logreg")) # breaks
```
The error message for the broken pipelines:
```
Error in self$assert(xs) : 
  Assertion on 'xs' failed: type: Must be element of set {'factor','integer','logical','numeric'}, but is 'NA'.
```
The `impute_missings` parameter breaks `liblinear` learners on most tasks (some examples: "german_credit", "iris", "sonar"). It works sometimes (`tsk("oml", 146821)`) - maybe because this task only has factor variables?
With `impute_missings = NULL`, the only problematic task I have found so far is `pima`.

I haven't found any issues with other learners so far (I tried `c("classif.ranger", "classif.xgboost", "classif.svm", "classif.liblinearl1l2svc",  "classif.liblinearl1logreg", "classif.cv_glmnet")`).

**Comment by mb706** [comment]
Thanks, apparently the fix was buggy.
