### ISSUE TITLE
Robust gap filling approach for time-series data 

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [mlr-org/mlr3pipelines#527]
Hi,

Can we have a gap filling approach within `mlr3pipelines`?
- Technically speaking there are some existing approaches for gap filling data and specially for a huge stack of satellite imagery data as in the libraries such as [Gdalcube](https://cran.r-project.org/web/packages/gdalcubes/index.html), which includes:
    - linear approaches like `mean`  
    - `repeat last seen observation`
    - etc.
but a robust method for such a challenge is missing. That  is why I asked about develop/adopting an approach to address the challenge.

Best, Mo
Here are some examples of the problem and solutions for your reference:
[LINK1](https://gking.harvard.edu/amelia)
[LINK2](https://bg.copernicus.org/articles/10/4055/2013/bg-10-4055-2013.pdf)
[LINK3](https://www.sciencedirect.com/science/article/pii/S0924271614002512)

**Comment by pfistfl** [comment]
I think this should go into (https://github.com/mlr-org/mlr3raster) @be-marc ?

**Comment by mohammadreza-sheykhmousa** [comment]
I did :)
