### ISSUE TITLE
GraphNode: has_no_nexts has_no_prevs has_next

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#54]
i am unsure if we need this, but maybe this makes code more readable

but we dont use this consistently
also its weird to have this "positively" and "negatively"

how about we have

is_lhs
is_rhs
?
that can also be easily negated. and this seems to be the context in which it is used most ofent?

**Comment by zzawadz** [comment]
Maybe: `has_lhs` and `has_rhs`?

But I agree.

**Comment by berndbischl** [comment]
Agree with the naming
