### ISSUE TITLE
pipeopvtreat doc name might be wrong 

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#542]
link in mlr3book is broken.

**Comment by pfistfl** [comment]
+ it does not have the tag `missing` which it should have?

**Comment by sumny** [comment]
> link in mlr3book is broken.

Hm, for me `mlr3book::ref("PipeOpVtreat")` returns:
```
"[`PipeOpVtreat`](https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_vtreat.html)"
```
which works for me
