### ISSUE TITLE
Unable to call functions from a pipeop in a graph

### ISSUE THREAD

**Issue by henrifnk** [mlr-org/mlr3pipelines#550]
If I construct a simple GraphLearner and train it like this
```r
graph <- GraphLearner$new(po("scale") %>>% lrn("regr.ranger"))
mt <- tsk("mtcars")
graph$train(task = mt)
```
I am not able to call on the functions defined in the learner like
```r
graph$oob_error()
```
nor do I have the possibility to call on the modell in a unified syntax like
```r
graph$modell$oob.error
```
also the following does not work anymore because the learner inside the graph is not trained
```r
graph$graph$pipeops[["regr.ranger"]]$learner$oob.error()
```
you would have to call instead:
```r
graph$state$model$regr.ranger$model$prediction.error
```

I'm asking this because it makes it hard to implement gerneric solutions for such workflows and it makes it impossible to call on the measure if you have a prediction:

```r
prediction <- graph$predict(task = mt)
prediction$score(msr("oob_error"))
```

Is there already a solution existing, which i am not aware of?

**Comment by mb706** [comment]
By now, we have the `$base_learner()` function for `GraphLearner`, which gives access to the learner at the end of the Graph.
```r
graph$base_learner()$model
graph$base_learner()$oob_error()
prediction$score(msr("oob_error"), learner = graph$base_learner())
```
