### ISSUE TITLE
Should PipeOpEncode also work on character?

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#555]

**Comment by mb706** [comment]
I don't think we should that, for the same reason that we don't have this for discrete numeric columns: Semantically, `character` columns are not to be encoded. When one encounters a `character` columns that should be encoded, then the column has the wrong type and should be converted. The canonical way of converting is
```r
po("colapply", applicator = as.factor)
```
(possibly followed by fixfactors or other).

We may want to have a test whether character->factor->encode works, factors in R are a difficult topic sometimes.

**Comment by pfistfl** [comment]
I can agree. I guess this is then documented here.
I find it a little cumbersome to always have to include this line, as treating it as a factor is what people wanna do in most cases, but 
this is a simple enough solution.
