### ISSUE TITLE
PipeOpTextVectorizer test fails on solaris

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#558]
[A single test currently fails on CRAN's Solaris instance](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/mlr3pipelines-00check.html):
```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test_pipeop_textvectorizer.R:34:3): PipeOpTextVectorizer - basic properties ──
  all(dt2[1, paste0("txt.", strs), with = FALSE] == 1) is not TRUE
  
  `actual`: FALSE
  `expected`: TRUE
  
  [ FAIL 1 | WARN 0 | SKIP 78 | PASS 10014 ]
  Error: Test failures
  Execution halted
```

Not yet sure if this is a Solaris problem or a general problem with an updated package and the Solaris CRAN test was just run more recently.

This happens here:
https://github.com/mlr-org/mlr3pipelines/blob/b95db5fefccb7a0d2cd8a839a9be3c64d43cc789/tests/testthat/test_pipeop_textvectorizer.R#L34

@pfistfl do you know if something recently happened with the things that we are using in PipeOpTextVectorizer, or why it could fail in Solaris?

**Comment by pfistfl** [comment]
Could it be a rare stochastic error?
It could theoretically sample the same 3 char string twice which would make this test fail. 
(If I am not mistaken...)

We should perhaps make those unit tests non-stochastic

**Comment by mb706** [comment]
Are there plausible random instances where the test fails? e.g. columns that end up being 0 and get removed?

**Comment by pfistfl** [comment]
#563 should solve it!

**Comment by mb706** [comment]
Seems to work now, thanks!
