### ISSUE TITLE
Graph: map function in parallel?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#56]
should this actually be parallelizable? currently i think it isnt because of the way we traverse the graph. can we do that smarter?

should we collect all nodes in a list? then map the function at the end?
actually being able to treat the graph as a list might be nice anyway....?

**Comment by zzawadz** [comment]
Yup. We can store list of all nodes in a topo order. It will also simplifies some other functions like `find_by_id`, and `[[` because there will be no need to traverse the graph to find a node, just O(1) operation.

**Comment by berndbischl** [comment]
But that implies that we need to maintain that list? If the graph is changed

**Comment by zzawadz** [comment]
Unfortunately yes.

I should not be a problem for `%>>%`, because we can update the list after each step. But if the user would want to construct the graph from `GraphNode` he will probably need to call `Graph$refresh()` or something like that (`Graph$compile()`?).

**Comment by berndbischl** [comment]
well we could also "discourage" the use "direct graphnode" operations for users, and simply encourage the use of ">>"

we would also document what needs to be taken care of / considered, if you really work on the nodes
(like callling set_next manually / by programming). we can then do this on the inside, and experts can still rely on this, but users dont do bad mistakes

**Comment by zzawadz** [comment]
Yup. 

I think that having two apis for creating a graph is quite ok - as you said - one will be for pros;)

I think that normal user will not even see the `set_next` method because it is a method of the GraphNode, and in the `>>` approach GraphNodes are hidden from the user.

**Comment by berndbischl** [comment]
i will open an alternative issue for the same goal
