### ISSUE TITLE
can we delegate the whole graph stuff to a well written library?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#58]
options:
a) igraph
b) boost graph
c) lemon ?
https://stackoverflow.com/questions/4917401/lemon-graph-library-on-r-using-rcpp

**Comment by zzawadz** [comment]
I don't know if we need this. Do we need a lot of graph operations? I can think of:
- topo sort?
- traverse?
- iterator?
Anything else?

**Comment by berndbischl** [comment]
not now
