### ISSUE TITLE
we should define how threshold tuning should look like

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#59]

**Comment by pfistfl** [comment]
We need a decision here.

I will write down options to base our decision on:

1. Use implementation similar to old `mlr`: 
    We simply tune the threshold of a `PredictionClassif` to optimize for a given `measure` 
    during training.
  - **Pro**
    - Fast
    - Simple implementation
    - Easy  to understand and adapt
    - Fits in all standard workflows.
  - **Con**
    - Might overfit
-  **Comments**
   - We should also expose the `threshold` as a numeric hyperparameter which can be 
     optimized during tuning. 
   - We could also penalize the thresholds, i.e. force them to be close to the trainset distribution
     or something. 

2. Optimize `threshold` using  `learner_cv`:
  - `train`: Fit a CV-Learner, get its prediction(s) and compute optimal thresholds from those.
  - `predict`: Set the threshold for the `Prediction` of the learner.
  - **Pro**
    - Robust
  - **Con**
    - Expensive (Requires CV) 
    - Does not fit the current scheme, i.e. what does the process look like?
      `PipeOpLearnerCV %>>% PipeOpTuneThreshold %>>% ???` 
      `PipeOpLearnerCV(tune_threshold = TRUE)`

**Comment by pfistfl** [comment]
Related Issues:
https://github.com/mlr-org/mlr3book/issues/117
https://github.com/mlr-org/mlr3book/issues/135

@mb706
Any comments? I think we might want both! If I get the ok, I 'd start coding them up.

**Comment by mllg** [comment]
I already have some threshold tuning code somewhere ...


https://github.com/mlr-org/mlr3/compare/threshold

IIRC the interface is just not clear:

* PipeOpTuneThreshold
* New virtual hyperparameter of LearnerClassif? (`tune_threshold` = `TRUE`)
* `AutoTuneThreshold` like `AutoTuner`?

**Comment by berndbischl** [comment]
Might wanna make this a prio issue for the workshop

**Comment by pfistfl** [comment]
Which means we also should specify the interface beforehand.

Proposal: 
  - Use `PipeOpTuneThreshold`: This exposes a `threshold` hyperparameter. It auto-tunes the threshold parameter if `threshold` is set to `'auto'` (the default).
    We can also just supply a `threshold` param from the outside, e.g. during tuning, in which case nothing happens.

Open Question:
- How would this look like for the `multiclass` case?
  Proposal: Threshold is then a param of length `nclass - 1L`, we can then pull it apart using a `trafo`.

**Comment by mb706** [comment]
We could just implement both a PipeOp using a LearnerCV and do resampled ("proper") threshold tuning, as well as one which exports a thresholding hyperparameter which can be tuned.

**Comment by mb706** [comment]
Split this into two issues #350 and #351
