### ISSUE TITLE
Implement try(Catch) pipeop

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3pipelines#60]
```
                   tryTrain+---------+
                +--------->+         |
                |tryPredict| nextOpA |
          +--------------->+         |
+---------+tryOp|          +---------+
          +-----+
                +--------->----------+
                |catchTrain|         |
                +--------->+ nextOpB |
               catchPredict|         |
                           +---------+
```
Cases

* Train of nextOpA works, we can use nextOpA for prediction
* Train of nextOpA fails, do something with error (or not) and train nextOpB. we have to use nextOpB for prediction
* Train of nextOpA works, we can use nextOpA for prediction but this prediction fails. Now what? Actually you would like to go back in time and use train nextOpB but this is not possible during training.
--> So we need a tryPredictPipeop as well or we have a 3rd edge in tryOp for predictFail? Do we have pipeOps?

**Comment by berndbischl** [comment]
not now
