### ISSUE TITLE
GraphLearner could have an AB shortcut for `$graph$pipeops`

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3pipelines#600]
E.g that one can directly do `GraphLearner$pipeops()` instead of `GraphLearner$graph$pipeops`.

cc @berndbischl

**Comment by mb706** [comment]
probably want to forward a few ABs and getters, but most likely not setters?

**Comment by advieser** [comment]
Possible candidates: 
- Fields:
  - `pipeops`
  - `edges`
  - `is_trained`: For `glrn$graph_model$is_trained`. Does that make sense?
  - `lhs` and `rhs`
  - `input` and `output`
- Methods:
  - `ids`
  - `plot`

**Comment by mb706** [comment]
let's leave it at `pipeops`, `edges`, `ids`, and `plot`. Should take `graph_model$pipeops`, for the others it can be `graph$...`
