### ISSUE TITLE
Add field "man" + method "help()"

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#649]
In mlr3 you can now always call `object$help()` to open the associated help page. The respective man page is stored in field "man". 

I guess this is easier for the user than to teach him our conventions of the help page name pattern.
Would be great to have for all pipeops and pipelines.

**Comment by mb706** [comment]
why not overload the `?`-operator (is it not possible)? Also would `$help()` not just call `help(class(self)[[1]])` or something like this, what does `man` do?

**Comment by mllg** [comment]
Sometimes we have multiple object and man pages for the same class, e.g. if they only differ by a hyperpar.

Merged by @be-marc .

**Comment by mb706** [comment]
> multiple man pages for the same class

example? 

Shouldn't `class(self)[[1]]` then at least be the default instead of copy-pasting it in every `initialize()` call?

**Comment by mllg** [comment]
One example would be the MeasureSimple class in mlr3.

And yes you can pick a different default.

**Comment by mb706** [comment]
Does the `man` slot get used anywhere besides `$help()`?
