### ISSUE TITLE
Add field label to PipeOp

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3pipelines#650]
We use the label in `as.data.table()` methods and for the website, but having a label is good at many points.

**Comment by mllg** [comment]
Merged by @be-marc .

**Comment by mb706** [comment]
So the label is usually the title of the corresponding `man`-page? What is it used for?

**Comment by mllg** [comment]
E.g., `as.data.table()` converters. Dictionaries will also support grepping on the label in the future.
