### ISSUE TITLE
PipeOpCollapseFactors hyperparameters

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3pipelines#709]
There should be another option besides `no_collapse_above_prevalence` which uses absolute count.

**Comment by mb706** [comment]
initialized to `Inf`, should have lower bound 1, no upper bound.

**Comment by mb706** [comment]
(lower bound 1 would mean only factors that occur once are collapsed)

**Comment by mb706** [comment]
Needs `special_vals` for this, otherwise `Inf` is not accepted by `p_int()`:
```r
p_int(1, special_vals = list(Inf))
```

**Comment by advieser** [comment]
closed by https://github.com/mlr-org/mlr3pipelines/pull/840
