### ISSUE TITLE
PipeOp to try repair predicting with unseen factor levels

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#71]
problem: quite often, a learner breaks, because it sees SOME prediction in a larger table, which contains new, unseen factor levels. in such a case the predict of the underlying learner fails, completely.

see reprex here:
https://github.com/mlr-org/mlr3/issues/97

this is really annoying. especially as this can happen on only a few observations, but we still 100% fail the complete prediction. 

current options are: the mlr3 fallback learner. that does not really help. because this produces now fallback predictions on the complete test set. 

here is MAYBE a better option.

PipOpUnseenLevels

before we go into the learner, we can on-training, store which levels are present in each factor. 

PipOpUnseenLevels
train: task--stored-levels--->task
predict: task-->stored-levels-->task

train: simply stores a list, one element per factor feature, with the seen level
predict: does through all observations. for each observation where we see "unseen" levels, we create a random row, by sampling from the marginals of the columns.
that is a bit hacky, but should work?

**Comment by prockenschaub** [comment]
By "random row" you mean that for an observation with an unseen level we samplw every variable of  from the marginals, even those variables for which the observed value was within the training sample, or just replace the unseen value itself with a draw from its own column marginal?

If I were to use this PipeOp, I would personally favour a more deterministic approach, either by filtering out those observations during prediction that contain a value that wasn't seen during training (ideally with warning) or by prespecifying a category that should be used if a new value is seen (the specification could say "marginals", which would include the second case in my question above)

**Comment by mb706** [comment]
Note we have the POBackupLearner for something like this: https://github.com/mlr-org/mlr3pipelines/pull/204

**Comment by pfistfl** [comment]
This should be solved via `fixfactors` and `imputation`. 
See e.g.
https://mlr3gallery.mlr-org.com/basics_pipelines_titanic/

**Comment by mb706** [comment]
together with the robustify pipeline this is probably as good as it gets.

**Comment by davidbudzynski** [comment]
sorry to necrobump this, but how can I use robustify and fixfactors together? I seem to get an error trying to do the following: 
```
> as_learner(
+         ppl("robustify") %>>%
+         po("fixfactors") %>>%
+         lrn("classif.log_reg",predict_type = "prob")
+ )
Error in gunion(list(g1, g2), in_place = c(TRUE, TRUE)) : 
  Assertion on 'ids of pipe operators of graphs' failed: Must have unique names, but element 15 is duplicated.
```
