### ISSUE TITLE
check the system for PipeOp channel data types, make sure we distinguish between train and predict

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#76]
this is API specs, and currently not well implemented.
we should also implement a SIMPLE check whether connected graph node are compatible

**Comment by mb706** [comment]
Needs some UI specs, see [discussion in slack](https://mlr-org.slack.com/archives/CDPJMANR3/p1548938519124600).

**Comment by mb706** [comment]
done in 839346f5c7a

Note new exported functions `add_class_hierarchy_cache`, `reset_class_hierarchy_cache`.
