### ISSUE TITLE
Discuss naming of functions and classes

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3pipelines#8]
Quick template, will add more later

- R6 Class: PipeOp
  Object: Naming: `par_set` or `parset` ? same for `par_vals`.

**Comment by pfistfl** [comment]
Naming: It is a little confusing that we speak of GraphNodes and PipeOp's.
       We could think of constistent naming, i.e.Pipeline -> Pipe -> PipeOp
       Pipes could then be: [PipeFanOut], [PipeMultiplexer] [PipeMerge] and [PipeSimple]

**Comment by berndbischl** [comment]
we really need to fix the names now
