### ISSUE TITLE
Linear, Aggreagte and BroadCast should probably be sublcasses of PipeOp

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#82]

**Comment by mb706** [comment]
I don't think these are the kind of subclasses we should be making; the current PipeOp is versatile in how many inputs and outputs it can accept.

**Comment by berndbischl** [comment]
where is the downside? you can still inherit from the base class so you lose nothing? 

and that structure is really "in" our current system?

**Comment by berndbischl** [comment]
lets reopen if we can come up with an argument why these classes would help in code

**Comment by berndbischl** [comment]
for completeness sake we could also put this in pipeop.R

is_broadcast
is_linear
is_aggreagtor
