### ISSUE TITLE
Don't need to define `dictionary_sugar_inc_get` and ``dictionary_sugar_inc_mget`` in `utils.R`

### ISSUE THREAD

**Issue by advieser** [mlr-org/mlr3pipelines#831]
As far as I can see, we don't need these anymore since the referenced PR (https://github.com/mlr-org/mlr3misc/pull/80) got merged into misc two years ago.
https://github.com/mlr-org/mlr3pipelines/blob/e52085f8a2be534da68fcc02647bbf63c7d1b010/R/utils.R#L116-L131
https://github.com/mlr-org/mlr3pipelines/blob/e52085f8a2be534da68fcc02647bbf63c7d1b010/R/utils.R#L133-L145

**Comment by mb706** [comment]
Yes, I think it can be removed

**Comment by advieser** [comment]
Closed by https://github.com/mlr-org/mlr3pipelines/pull/832
