### ISSUE TITLE
we need to define a (scalable) system for PipeOp unit tests

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3pipelines#90]
i guess we dont want to test all of them manually?

**Comment by mllg** [comment]
AFAICT, we already have a lot of automatic unit tests in place.

**Comment by mb706** [comment]
Tests in pipeop are still a mess and need improvement

**Comment by mb706** [comment]
Also TODO: 
check that tests except autotests are actually run on cran (https://github.com/mlr-org/mlr3pipelines/issues/289)
